/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface.DoctorAdministration;

import BusinessModel.Ecosystem;
import BusinessModel.Doctor.Dr;
import BusinessModel.Roles.Doctor_role;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import MainUserInterface.ReceptionRole.ReceptionWorkArea;

/**
 *
 * @author daddy
 */
public class CreateDoc extends javax.swing.JPanel {

    /**
     * Creates new form DoctorAdministratorWorkAreaJPanel
     */
    private final JPanel userProCont;
    private final Ecosystem ecoSystem;
    User userAcc;
    private Dr imgDoc;

    public CreateDoc(JPanel userProcessContainer, User user, Ecosystem system) {
        initComponents();
        this.userAcc = user;
        this.userProCont = userProcessContainer;
        this.ecoSystem = system;
        this.imgDoc = new Dr();

        genderDropDown.removeAllItems();
        genderDropDown.addItem("Male");
        genderDropDown.addItem("Female");
        genderDropDown.addItem("Other");

        populateTable();
    }

    private void populateTable() {
        // DefaultTableModel model = (DefaultTableModel) ManageCustomersTable.getModel();

        //model.setRowCount(0);
        for (User user : ecoSystem.getUserAccountDirectory().getUserAccountList()) {

            if ("Business.Role.DoctorRole".equals(user.getRole().getClass().getName())) {
                Object[] row = new Object[3];
                row[1] = user.getUsername();
                row[2] = user.getPassword();
                // model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lNameTxt = new javax.swing.JTextField();
        addressTxt = new javax.swing.JTextField();
        UserNameLbl = new javax.swing.JLabel();
        workIDTxt = new javax.swing.JTextField();
        DoctorWorkIDLbl = new javax.swing.JLabel();
        lblExperience = new javax.swing.JLabel();
        mobileTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        userNameTxt = new javax.swing.JTextField();
        FirstNameLbl = new javax.swing.JLabel();
        lblSpeciality = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        DateOfBirthLbl = new javax.swing.JLabel();
        expTxt = new javax.swing.JTextField();
        PhoneNoLbl = new javax.swing.JLabel();
        GenderLbl = new javax.swing.JLabel();
        PasswordLbl = new javax.swing.JLabel();
        lLastNameLbl = new javax.swing.JLabel();
        fNameTxt = new javax.swing.JTextField();
        lblRestaurantInfo = new javax.swing.JLabel();
        mailTxt = new javax.swing.JTextField();
        EmailLbl = new javax.swing.JLabel();
        specializationTxt = new javax.swing.JTextField();
        AddressLbl = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        genderDropDown = new javax.swing.JComboBox<>();
        ErrorPhoneLbl = new javax.swing.JLabel();
        ErrorEmailLbl = new javax.swing.JLabel();
        lblErrorAddress = new javax.swing.JLabel();
        lblErrorSpecialist = new javax.swing.JLabel();
        lblErrorWorkExperience = new javax.swing.JLabel();
        ErrorUserNameLbl = new javax.swing.JLabel();
        ErrorPasswordLbl = new javax.swing.JLabel();
        lblPhotoImage = new javax.swing.JLabel();
        uploadDocImgBtn = new javax.swing.JButton();
        lblErrorDoctorWorkID = new javax.swing.JLabel();
        birthDateCalender = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(51, 51, 51));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lNameTxt.setBackground(new java.awt.Color(153, 153, 153));
        lNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtActionPerformed(evt);
            }
        });
        lNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxtKeyReleased(evt);
            }
        });
        add(lNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 490, 170, 30));

        addressTxt.setBackground(new java.awt.Color(153, 153, 153));
        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        addressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxtKeyReleased(evt);
            }
        });
        add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, 170, 70));

        UserNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        UserNameLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        UserNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        UserNameLbl.setText("User Name");
        add(UserNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 100, -1));

        workIDTxt.setBackground(new java.awt.Color(153, 153, 153));
        workIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                workIDTxtActionPerformed(evt);
            }
        });
        workIDTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                workIDTxtKeyReleased(evt);
            }
        });
        add(workIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 440, 170, 30));

        DoctorWorkIDLbl.setBackground(new java.awt.Color(255, 255, 255));
        DoctorWorkIDLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        DoctorWorkIDLbl.setForeground(new java.awt.Color(255, 255, 255));
        DoctorWorkIDLbl.setText("Doctor Work ID");
        add(DoctorWorkIDLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, -1, 20));

        lblExperience.setBackground(new java.awt.Color(255, 255, 255));
        lblExperience.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblExperience.setForeground(new java.awt.Color(255, 255, 255));
        lblExperience.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExperience.setText("Experience");
        add(lblExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 540, 127, 20));

        mobileTxt.setEditable(false);
        mobileTxt.setBackground(new java.awt.Color(153, 153, 153));
        mobileTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTxtActionPerformed(evt);
            }
        });
        mobileTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileTxtKeyReleased(evt);
            }
        });
        add(mobileTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 290, 170, 30));

        submitBtn.setBackground(new java.awt.Color(51, 51, 255));
        submitBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 590, 100, 30));

        userNameTxt.setBackground(new java.awt.Color(153, 153, 153));
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        userNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameTxtKeyReleased(evt);
            }
        });
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 170, 30));

        FirstNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        FirstNameLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        FirstNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        FirstNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        FirstNameLbl.setText("First Name");
        add(FirstNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 110, -1));

        lblSpeciality.setBackground(new java.awt.Color(255, 255, 255));
        lblSpeciality.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblSpeciality.setForeground(new java.awt.Color(255, 255, 255));
        lblSpeciality.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSpeciality.setText("Specialist");
        add(lblSpeciality, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 110, 20));

        passwordTxt.setBackground(new java.awt.Color(153, 153, 153));
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtKeyReleased(evt);
            }
        });
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 440, 170, 30));

        DateOfBirthLbl.setBackground(new java.awt.Color(255, 255, 255));
        DateOfBirthLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        DateOfBirthLbl.setForeground(new java.awt.Color(255, 255, 255));
        DateOfBirthLbl.setText("Date of Birth");
        add(DateOfBirthLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 550, 120, -1));

        expTxt.setBackground(new java.awt.Color(153, 153, 153));
        expTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                expTxtActionPerformed(evt);
            }
        });
        expTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                expTxtKeyReleased(evt);
            }
        });
        add(expTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 540, 170, 30));

        PhoneNoLbl.setBackground(new java.awt.Color(255, 255, 255));
        PhoneNoLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        PhoneNoLbl.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNoLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PhoneNoLbl.setText("Phone Number");
        add(PhoneNoLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 290, -1, -1));

        GenderLbl.setBackground(new java.awt.Color(255, 255, 255));
        GenderLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        GenderLbl.setForeground(new java.awt.Color(255, 255, 255));
        GenderLbl.setText("Gender");
        add(GenderLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 250, -1, -1));

        PasswordLbl.setBackground(new java.awt.Color(0, 0, 0));
        PasswordLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        PasswordLbl.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLbl.setText("Password");
        add(PasswordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 440, 90, -1));

        lLastNameLbl.setBackground(new java.awt.Color(0, 0, 0));
        lLastNameLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lLastNameLbl.setForeground(new java.awt.Color(255, 255, 255));
        lLastNameLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lLastNameLbl.setText("Last Name");
        add(lLastNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 490, 110, -1));

        fNameTxt.setBackground(new java.awt.Color(153, 153, 153));
        fNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTxtActionPerformed(evt);
            }
        });
        fNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxtKeyReleased(evt);
            }
        });
        add(fNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 190, 170, 30));

        lblRestaurantInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantInfo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        lblRestaurantInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantInfo.setText("ADD A DOCTOR");
        add(lblRestaurantInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 310, -1));

        mailTxt.setBackground(new java.awt.Color(153, 153, 153));
        mailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mailTxtActionPerformed(evt);
            }
        });
        mailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mailTxtKeyReleased(evt);
            }
        });
        add(mailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 600, 170, 30));

        EmailLbl.setBackground(new java.awt.Color(255, 255, 255));
        EmailLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        EmailLbl.setForeground(new java.awt.Color(255, 255, 255));
        EmailLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EmailLbl.setText("Email");
        add(EmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 600, 60, -1));

        specializationTxt.setBackground(new java.awt.Color(153, 153, 153));
        specializationTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                specializationTxtActionPerformed(evt);
            }
        });
        specializationTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                specializationTxtKeyReleased(evt);
            }
        });
        add(specializationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 170, 30));

        AddressLbl.setBackground(new java.awt.Color(255, 255, 255));
        AddressLbl.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        AddressLbl.setForeground(new java.awt.Color(255, 255, 255));
        AddressLbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        AddressLbl.setText("Address");
        add(AddressLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 127, 30));

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 24)); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 715, -1, -1));

        jLabel4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Qualification  Information ");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(666, 370, 330, 30));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, 370, 20));

        genderDropDown.setBackground(new java.awt.Color(153, 153, 153));
        genderDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderDropDownActionPerformed(evt);
            }
        });
        add(genderDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, 170, 30));

        ErrorPhoneLbl.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        ErrorPhoneLbl.setForeground(new java.awt.Color(255, 51, 51));
        ErrorPhoneLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ErrorPhoneLblKeyReleased(evt);
            }
        });
        add(ErrorPhoneLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 330, 170, 20));

        ErrorEmailLbl.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        ErrorEmailLbl.setForeground(new java.awt.Color(255, 51, 51));
        ErrorEmailLbl.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/doctor gif.gif"))); // NOI18N
        ErrorEmailLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ErrorEmailLblKeyReleased(evt);
            }
        });
        add(ErrorEmailLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 140, 230, 130));

        lblErrorAddress.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorAddress.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorAddressKeyReleased(evt);
            }
        });
        add(lblErrorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 460, 210, 30));

        lblErrorSpecialist.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorSpecialist.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorSpecialist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorSpecialistKeyReleased(evt);
            }
        });
        add(lblErrorSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 530, 170, 20));

        lblErrorWorkExperience.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorWorkExperience.setForeground(new java.awt.Color(255, 51, 51));
        lblErrorWorkExperience.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/adddoctor.png"))); // NOI18N
        lblErrorWorkExperience.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorWorkExperienceKeyReleased(evt);
            }
        });
        add(lblErrorWorkExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 20, 70, 70));

        ErrorUserNameLbl.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        ErrorUserNameLbl.setForeground(new java.awt.Color(255, 51, 51));
        ErrorUserNameLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ErrorUserNameLblKeyReleased(evt);
            }
        });
        add(ErrorUserNameLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 200, 26));

        ErrorPasswordLbl.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        ErrorPasswordLbl.setForeground(new java.awt.Color(255, 51, 51));
        ErrorPasswordLbl.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                ErrorPasswordLblKeyReleased(evt);
            }
        });
        add(ErrorPasswordLbl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 480, 200, 26));

        lblPhotoImage.setText("doctor_Image");
        add(lblPhotoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 150, 180, 200));

        uploadDocImgBtn.setBackground(new java.awt.Color(51, 51, 255));
        uploadDocImgBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 14)); // NOI18N
        uploadDocImgBtn.setForeground(new java.awt.Color(255, 255, 255));
        uploadDocImgBtn.setText("Upload Image");
        uploadDocImgBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadDocImgBtnActionPerformed(evt);
            }
        });
        add(uploadDocImgBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 310, -1, -1));
        add(lblErrorDoctorWorkID, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 470, 170, 20));

        birthDateCalender.setBackground(new java.awt.Color(153, 153, 153));
        birthDateCalender.setDateFormatString("MM-dd-yyyy");
        birthDateCalender.setMaxSelectableDate(new Date());
        add(birthDateCalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 540, 180, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/icons8-qualification-45.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 360, 40, 40));
    }// </editor-fold>//GEN-END:initComponents

    private void lNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtActionPerformed

    private void workIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_workIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_workIDTxtActionPerformed

    private void mobileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTxtActionPerformed

    private void mailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mailTxtActionPerformed

    private void specializationTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_specializationTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_specializationTxtActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void expTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_expTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_expTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if (ecoSystem.getUserAccountDirectory().checkIfUsernameIsUnique(passwordTxt.getText())
                && (lblErrorAddress.getText() == null || lblErrorAddress.getText().equals(""))
                && (ErrorEmailLbl.getText() == null || ErrorEmailLbl.getText().equals(""))
                && (ErrorPasswordLbl.getText() == null || ErrorPasswordLbl.getText().equals(""))
                && (ErrorPhoneLbl.getText() == null || ErrorPhoneLbl.getText().equals(""))
                && (ErrorUserNameLbl.getText() == null || ErrorUserNameLbl.getText().equals(""))     
                ) {
            Dr doctor = new Dr(passwordTxt.getText());
            doctor.setdocFirstName(fNameTxt.getText());
            doctor.setdocLastName(lNameTxt.getText());
            doctor.setdocAge((CalculateAge(birthDateCalender.getDate(), java.util.Calendar.getInstance().getTime())));
            doctor.setdocGender((String) genderDropDown.getSelectedItem());
            doctor.setdocWorkID(workIDTxt.getText());
            doctor.setdocAddress(addressTxt.getText());
            doctor.setdocMNo(mobileTxt.getText());
            //doctor.setDateofBirth(txtDateOfBirth.getText());
            doctor.setdocEmail(mailTxt.getText());
            doctor.setdocSpecialization(specializationTxt.getText());
            doctor.setdocExp(expTxt.getText());
            doctor.setdocUserName(passwordTxt.getText());
            imgDoc = doctor;
            ecoSystem.getUserAccountDirectory().createUser(passwordTxt.getText(), userNameTxt.getText(), null, new Doctor_role());
            ecoSystem.getDoctorDirect().createDoctor(doctor);
            JOptionPane.showMessageDialog(null, "Doctor added.");
            
            DocAdminWorkArea doctorAdminWorkArea = new DocAdminWorkArea(userProCont, userAcc, ecoSystem);
            userProCont.add("Doctor Admin Work Area", doctorAdminWorkArea);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);
            
        } else 
        {
            JOptionPane.showMessageDialog(null, "Please Fill Correct Details");
        }
        
        

    }//GEN-LAST:event_submitBtnActionPerformed

    public int CalculateAge(Date birthDate, Date currentDate) {
        // validate inputs ...                                                                               
        DateFormat formatter = new SimpleDateFormat("yyyyMMdd");
        int d1 = Integer.parseInt(formatter.format(birthDate));
        int d2 = Integer.parseInt(formatter.format(currentDate));
        int age = (d2 - d1) / 10000;
        return age;
    }

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void fNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTxtActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_fNameTxtActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed

    private void genderDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderDropDownActionPerformed

    private void fNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(fNameTxt.getText());
        if (!match.matches()) {
            //lblErrorFname.setText("Wrong Input");
        } else {
            //lblErrorFname.setText(null);
        }
    }//GEN-LAST:event_fNameTxtKeyReleased

    private void lNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(lNameTxt.getText());
        if (!match.matches()) {
            //lblErrorLname.setText("Wrong Input");
        } else {
            //lblErrorLname.setText(null);
        }
    }//GEN-LAST:event_lNameTxtKeyReleased

    private void ErrorPhoneLblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ErrorPhoneLblKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorPhoneLblKeyReleased

    private void ErrorEmailLblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ErrorEmailLblKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorEmailLblKeyReleased

    private void lblErrorAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorAddressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorAddressKeyReleased

    private void lblErrorSpecialistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorSpecialistKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorSpecialistKeyReleased

    private void lblErrorWorkExperienceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorWorkExperienceKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorWorkExperienceKeyReleased

    private void ErrorUserNameLblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ErrorUserNameLblKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorUserNameLblKeyReleased

    private void ErrorPasswordLblKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ErrorPasswordLblKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_ErrorPasswordLblKeyReleased

    private void workIDTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_workIDTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(workIDTxt.getText());
        if (!match.matches()) {
            lblErrorDoctorWorkID.setText("Wrong Input");
        } else {
            lblErrorDoctorWorkID.setText(null);
        }
    }//GEN-LAST:event_workIDTxtKeyReleased

    private void mobileTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9 +()-]{10,18}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(mobileTxt.getText());
        if (!match.matches()) {
            ErrorPhoneLbl.setText("Wrong Input");
        } else {
            ErrorPhoneLbl.setText(null);
        }
    }//GEN-LAST:event_mobileTxtKeyReleased

    private void mailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mailTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(mailTxt.getText());
        if (!match.matches()) {
            ErrorEmailLbl.setText("Wrong Input");
        } else {
            ErrorEmailLbl.setText(null);
        }
    }//GEN-LAST:event_mailTxtKeyReleased

    private void addressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(addressTxt.getText());
        if (!match.matches()) {
            lblErrorAddress.setText("Wrong Input");
        } else {
            lblErrorAddress.setText(null);
        }
    }//GEN-LAST:event_addressTxtKeyReleased

    private void specializationTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_specializationTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(specializationTxt.getText());
        if (!match.matches()) {
            lblErrorSpecialist.setText("Wrong Input");
        } else {
            lblErrorSpecialist.setText(null);
        }
    }//GEN-LAST:event_specializationTxtKeyReleased

    private void expTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_expTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(expTxt.getText());
        if (!match.matches()) {
            lblErrorWorkExperience.setText("Wrong Input");
        } else {
            lblErrorWorkExperience.setText(null);
        }
    }//GEN-LAST:event_expTxtKeyReleased

    private void userNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(userNameTxt.getText());
        if (!match.matches()) {
            ErrorPasswordLbl.setText("Wrong Input");
        } else {
            ErrorPasswordLbl.setText(null);
        }
    }//GEN-LAST:event_userNameTxtKeyReleased

    private void passwordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(passwordTxt.getText());
        if (!match.matches()) {
            ErrorUserNameLbl.setText("Wrong Input");
        } else {
            ErrorUserNameLbl.setText(null);
        }
    }//GEN-LAST:event_passwordTxtKeyReleased

    private void uploadDocImgBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadDocImgBtnActionPerformed
        // TODO add your handling code here:
         // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            imgDoc.setdocImageUrl(selectedImagePath);

            ImageIcon ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblPhotoImage.getWidth(), lblPhotoImage.getHeight(), Image.SCALE_SMOOTH);
            lblPhotoImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_uploadDocImgBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AddressLbl;
    private javax.swing.JLabel DateOfBirthLbl;
    private javax.swing.JLabel DoctorWorkIDLbl;
    private javax.swing.JLabel EmailLbl;
    private javax.swing.JLabel ErrorEmailLbl;
    private javax.swing.JLabel ErrorPasswordLbl;
    private javax.swing.JLabel ErrorPhoneLbl;
    private javax.swing.JLabel ErrorUserNameLbl;
    private javax.swing.JLabel FirstNameLbl;
    private javax.swing.JLabel GenderLbl;
    private javax.swing.JLabel PasswordLbl;
    private javax.swing.JLabel PhoneNoLbl;
    private javax.swing.JLabel UserNameLbl;
    private javax.swing.JTextField addressTxt;
    private com.toedter.calendar.JDateChooser birthDateCalender;
    private javax.swing.JTextField expTxt;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JComboBox<String> genderDropDown;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JLabel lLastNameLbl;
    private javax.swing.JTextField lNameTxt;
    private javax.swing.JLabel lblErrorAddress;
    private javax.swing.JLabel lblErrorDoctorWorkID;
    private javax.swing.JLabel lblErrorSpecialist;
    private javax.swing.JLabel lblErrorWorkExperience;
    private javax.swing.JLabel lblExperience;
    private javax.swing.JLabel lblPhotoImage;
    private javax.swing.JLabel lblRestaurantInfo;
    private javax.swing.JLabel lblSpeciality;
    private javax.swing.JTextField mailTxt;
    private javax.swing.JTextField mobileTxt;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField specializationTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JButton uploadDocImgBtn;
    private javax.swing.JTextField userNameTxt;
    private javax.swing.JTextField workIDTxt;
    // End of variables declaration//GEN-END:variables
}
