/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface.DoctorAdministration;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.Doctor.Dr;
import BusinessModel.Ecosystem;
import BusinessModel.Roles.RoleDoc;
import BusinessModel.Roles.RolePatient;
import BusinessModel.UserAccount.User;
import java.awt.Image;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daddy
 */
public class DocUpdate extends javax.swing.JPanel {

    /**
     * Creates new form DoctorAdministratorWorkAreaJPanel
     */
    private final JPanel userProCont;
    private final Ecosystem ecoSystem;
    User userAcc;
    Dr doc;
    public DocUpdate(JPanel userProcessContainer,User user, Ecosystem system, Dr d) {
        initComponents();
        this.userAcc = user;
        this.userProCont = userProcessContainer;
        this.ecoSystem = system;
        this.doc=d;
        txtAddress.setText(d.getdocAddress());
        txtAge.setText(Integer.toHexString(d.getdocAge()));
       birthDateCalender.setDate(d.getdocDOB());
        txtDoctorID.setText(d.getdocWorkID());
        txtEmail.setText(d.getdocEmail());
        txtExperience.setText(d.getdocExp());
        txtFirstName.setText(d.getdocFirstName());
        txtLastName.setText(d.getdocLastName());
        //txtGender.setText(d.getdocGender());
        txtPhoneNumber.setText(d.getdocMNo());
        txtSpecialist.setText(d.getdocSpecialization());
        txtUsername.setText(d.getdocUserName());
        GenderDropDownList.setSelectedItem(doc.getdocGender());
        
        GenderDropDownList.removeAllItems();
        GenderDropDownList.addItem("Male");
        GenderDropDownList.addItem("Female");
        GenderDropDownList.addItem("OthGenderDropDownLister");
    }

    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblRestaurantName = new javax.swing.JLabel();
        lblRestaurantInfo = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblPhoneNumber = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        lblAddress = new javax.swing.JLabel();
        txtAge = new javax.swing.JTextField();
        lblRestaurantName1 = new javax.swing.JLabel();
        lblPhoneNumber1 = new javax.swing.JLabel();
        txtDoctorID = new javax.swing.JTextField();
        lblAddress1 = new javax.swing.JLabel();
        txtPhoneNumber = new javax.swing.JTextField();
        lblRestaurantName2 = new javax.swing.JLabel();
        lblPhoneNumber2 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        lblAddress2 = new javax.swing.JLabel();
        txtSpecialist = new javax.swing.JTextField();
        lblAddress3 = new javax.swing.JLabel();
        txtAddress = new javax.swing.JTextField();
        lblAddress4 = new javax.swing.JLabel();
        txtExperience = new javax.swing.JTextField();
        txtUsername = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        birthDateCalender = new com.toedter.calendar.JDateChooser();
        GenderDropDownList = new javax.swing.JComboBox<>();
        lblErrorSpecialist = new javax.swing.JLabel();
        ErrorUserNameLbl1 = new javax.swing.JLabel();
        lblErrorFname2 = new javax.swing.JLabel();
        ErrorEmailLbl2 = new javax.swing.JLabel();
        ErrorPhoneLbl4 = new javax.swing.JLabel();
        lblErrorWorkExperience1 = new javax.swing.JLabel();
        lblErrorDoctorWorkID2 = new javax.swing.JLabel();
        lblErrorLname1 = new javax.swing.JLabel();
        lblErrorAddress1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 153, 204));

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRestaurantName.setBackground(new java.awt.Color(0, 0, 0));
        lblRestaurantName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblRestaurantName.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName.setText("First Name");
        jPanel1.add(lblRestaurantName, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 190, 113, -1));

        lblRestaurantInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantInfo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        lblRestaurantInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantInfo.setText("Update Doctor");
        jPanel1.add(lblRestaurantInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 40, 280, -1));

        txtFirstName.setBackground(new java.awt.Color(153, 153, 153));
        txtFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstNameActionPerformed(evt);
            }
        });
        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 190, 170, 33));

        lblPhoneNumber.setBackground(new java.awt.Color(0, 0, 0));
        lblPhoneNumber.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber.setText("Last Name");
        jPanel1.add(lblPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 190, 101, 20));

        txtLastName.setBackground(new java.awt.Color(153, 153, 153));
        txtLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLastNameActionPerformed(evt);
            }
        });
        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLastNameKeyReleased(evt);
            }
        });
        jPanel1.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 190, 185, 30));

        lblAddress.setBackground(new java.awt.Color(0, 0, 0));
        lblAddress.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress.setText("Age");
        jPanel1.add(lblAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 40, -1));

        txtAge.setEditable(false);
        txtAge.setBackground(new java.awt.Color(153, 153, 153));
        txtAge.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAgeActionPerformed(evt);
            }
        });
        jPanel1.add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 250, 170, 40));

        lblRestaurantName1.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantName1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblRestaurantName1.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName1.setText("Gender");
        jPanel1.add(lblRestaurantName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 250, 80, 30));

        lblPhoneNumber1.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPhoneNumber1.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber1.setText("Doctor Work ID");
        jPanel1.add(lblPhoneNumber1, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 130, -1, -1));

        txtDoctorID.setBackground(new java.awt.Color(153, 153, 153));
        txtDoctorID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDoctorIDActionPerformed(evt);
            }
        });
        txtDoctorID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtDoctorIDKeyReleased(evt);
            }
        });
        jPanel1.add(txtDoctorID, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 130, 185, 33));

        lblAddress1.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAddress1.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress1.setText("Phone Number");
        jPanel1.add(lblAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 147, 30));

        txtPhoneNumber.setBackground(new java.awt.Color(153, 153, 153));
        txtPhoneNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPhoneNumberActionPerformed(evt);
            }
        });
        txtPhoneNumber.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneNumberKeyReleased(evt);
            }
        });
        jPanel1.add(txtPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 380, 170, 30));

        lblRestaurantName2.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantName2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblRestaurantName2.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName2.setText("Date of Birth");
        jPanel1.add(lblRestaurantName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 370, 120, 30));

        lblPhoneNumber2.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPhoneNumber2.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber2.setText("Email");
        jPanel1.add(lblPhoneNumber2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 320, -1, -1));

        txtEmail.setBackground(new java.awt.Color(153, 153, 153));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });
        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        jPanel1.add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, 170, 30));

        lblAddress2.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAddress2.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress2.setText("Specialist");
        jPanel1.add(lblAddress2, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, -1, 50));

        txtSpecialist.setBackground(new java.awt.Color(153, 153, 153));
        txtSpecialist.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecialistActionPerformed(evt);
            }
        });
        txtSpecialist.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSpecialistKeyReleased(evt);
            }
        });
        jPanel1.add(txtSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 430, 180, 30));

        lblAddress3.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAddress3.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress3.setText("Address");
        jPanel1.add(lblAddress3, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 310, 80, 30));

        txtAddress.setBackground(new java.awt.Color(153, 153, 153));
        txtAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAddressActionPerformed(evt);
            }
        });
        txtAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAddressKeyReleased(evt);
            }
        });
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 310, 180, 30));

        lblAddress4.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAddress4.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress4.setText("Experience");
        jPanel1.add(lblAddress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 110, 30));

        txtExperience.setBackground(new java.awt.Color(153, 153, 153));
        txtExperience.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtExperienceActionPerformed(evt);
            }
        });
        txtExperience.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtExperienceKeyReleased(evt);
            }
        });
        jPanel1.add(txtExperience, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 440, 170, 30));

        txtUsername.setEditable(false);
        txtUsername.setBackground(new java.awt.Color(153, 153, 153));
        txtUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsernameActionPerformed(evt);
            }
        });
        txtUsername.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtUsernameKeyReleased(evt);
            }
        });
        jPanel1.add(txtUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 130, 174, 33));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 115, 33));

        updateBtn.setBackground(new java.awt.Color(51, 51, 255));
        updateBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 520, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/doctor gif2 resized.gif"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 220, 220));
        jPanel1.add(birthDateCalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 380, 180, -1));

        GenderDropDownList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel1.add(GenderDropDownList, new org.netbeans.lib.awtextra.AbsoluteConstraints(1122, 250, 180, -1));

        lblErrorSpecialist.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorSpecialist, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 470, 290, 30));

        ErrorUserNameLbl1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ErrorUserNameLbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 160, 320, 30));

        lblErrorFname2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorFname2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, 320, 30));

        ErrorEmailLbl2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ErrorEmailLbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 350, 310, 30));

        ErrorPhoneLbl4.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(ErrorPhoneLbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 410, 330, 30));

        lblErrorWorkExperience1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorWorkExperience1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 470, 340, 30));

        lblErrorDoctorWorkID2.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorDoctorWorkID2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 160, 270, 30));

        lblErrorLname1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorLname1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 220, 250, 30));

        lblErrorAddress1.setForeground(new java.awt.Color(255, 0, 0));
        jPanel1.add(lblErrorAddress1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 340, 350, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1542, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 841, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(2846, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLastNameActionPerformed

    private void txtDoctorIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDoctorIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDoctorIDActionPerformed

    private void txtPhoneNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPhoneNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPhoneNumberActionPerformed

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void txtSpecialistActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecialistActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecialistActionPerformed

    private void txtAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAddressActionPerformed

    private void txtExperienceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtExperienceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtExperienceActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        String name = txtFirstName.getText();
        String lastname = txtLastName.getText();
        String doctorId = txtDoctorID.getText();
        String address = txtAddress.getText();
        String phoneNumber = txtPhoneNumber.getText();
        String mail = txtEmail.getText();
        String specialist = txtSpecialist.getText();
        String exp = txtExperience.getText();
        String username = txtUsername.getText();
        if(name.isEmpty() || lastname.isEmpty() || doctorId.isEmpty() || address.isEmpty()
            || phoneNumber.isEmpty() || mail.isEmpty() || specialist.isEmpty() || exp.isEmpty()
            || username.isEmpty()){
            JOptionPane.showMessageDialog(this,
                "Enter all Fields",
                "Try Again",
                JOptionPane.ERROR_MESSAGE);
        }
        else
        {
        
       doc.setdocFirstName(txtFirstName.getText());
        doc.setdocLastName(txtLastName.getText());
       doc.setdocAge(CalculateAge(birthDateCalender.getDate(), java.util.Calendar.getInstance().getTime()));
        doc.setdocGender((String) GenderDropDownList.getSelectedItem());
        doc.setdocWorkID(txtDoctorID.getText());
        doc.setdocAddress(txtAddress.getText());
        doc.setdocMNo(txtPhoneNumber.getText());
        doc.setdocDOB(birthDateCalender.getDate());
        doc.setdocEmail(txtEmail.getText());
        doc.setdocSpecialization(txtSpecialist.getText());
        doc.setdocExp(txtExperience.getText());
        doc.setdocUserName(txtUsername.getText());
        JOptionPane.showMessageDialog(null, "Update Complete.");
        }
        
    }//GEN-LAST:event_updateBtnActionPerformed

    private void txtUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsernameActionPerformed

    private void txtUsernameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUsernameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtUsername.getText());
        if (!match.matches()) {
            ErrorUserNameLbl1.setText("Invalid!..Cannot be blank");
        } else {
           ErrorUserNameLbl1.setText(null);
        }
    }//GEN-LAST:event_txtUsernameKeyReleased

    private void txtFirstNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtFirstName.getText());
        if (!match.matches()) {
            lblErrorFname2.setText("Invalid!..Cannot be blank and no numbers");
        } else {
           lblErrorFname2.setText(null);
        }
                
    }//GEN-LAST:event_txtFirstNameKeyReleased

    private void txtFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameActionPerformed

    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtEmail.getText());
        if (!match.matches()) {
           ErrorEmailLbl2.setText("Invalid!..Should be in email format");
        } else {
            ErrorEmailLbl2.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    private void txtPhoneNumberKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneNumberKeyReleased
        // TODO add your handling code here:
        String PATTERN = "\\d{10}";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtPhoneNumber.getText());
        if (!match.matches()) {
            ErrorPhoneLbl4.setText("Invalid!..Should have only 10 digits");
        } else {
            ErrorPhoneLbl4.setText(null);
        }
    }//GEN-LAST:event_txtPhoneNumberKeyReleased

    private void txtExperienceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtExperienceKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtExperience.getText());
        if (!match.matches()) {
            lblErrorWorkExperience1.setText("Invalid!..Cannot be blank");
        } else {
            lblErrorWorkExperience1.setText(null);
        }
    }//GEN-LAST:event_txtExperienceKeyReleased

    private void txtDoctorIDKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDoctorIDKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtDoctorID.getText());
        if (!match.matches()) {
            lblErrorDoctorWorkID2.setText("Invalid!..Cannot be blank");
        } else {
            lblErrorDoctorWorkID2.setText(null);
        }
    }//GEN-LAST:event_txtDoctorIDKeyReleased

    private void txtLastNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtLastName.getText());
        if (!match.matches()) {
            lblErrorLname1.setText("Invalid!..Cannot be blank");
        } else {
           lblErrorLname1.setText(null);
        }
    }//GEN-LAST:event_txtLastNameKeyReleased

    private void txtAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAddressKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtAddress.getText());
        if (!match.matches()) {
            lblErrorAddress1.setText("Invalid!..Cannot be blank");
        } else {
            lblErrorAddress1.setText(null);
        }
    }//GEN-LAST:event_txtAddressKeyReleased

    private void txtSpecialistKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSpecialistKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtSpecialist.getText());
        if (!match.matches()) {
            lblErrorSpecialist.setText("Invalid!..Cannot be blank");
        } else {
            lblErrorSpecialist.setText(null);
        }
    }//GEN-LAST:event_txtSpecialistKeyReleased

    private void txtAgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAgeActionPerformed
public int CalculateAge(Date birthDate, Date currentDate) {
        // validate inputs ...                                                                               
        DateFormat formatter = new SimpleDateFormat("yyyyMMdd");
        int d1 = Integer.parseInt(formatter.format(birthDate));
        int d2 = Integer.parseInt(formatter.format(currentDate));
        int age = (d2 - d1) / 10000;
        return age;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ErrorEmailLbl2;
    private javax.swing.JLabel ErrorPhoneLbl4;
    private javax.swing.JLabel ErrorUserNameLbl1;
    private javax.swing.JComboBox<String> GenderDropDownList;
    private com.toedter.calendar.JDateChooser birthDateCalender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblAddress1;
    private javax.swing.JLabel lblAddress2;
    private javax.swing.JLabel lblAddress3;
    private javax.swing.JLabel lblAddress4;
    private javax.swing.JLabel lblErrorAddress1;
    private javax.swing.JLabel lblErrorDoctorWorkID2;
    private javax.swing.JLabel lblErrorFname2;
    private javax.swing.JLabel lblErrorLname1;
    private javax.swing.JLabel lblErrorSpecialist;
    private javax.swing.JLabel lblErrorWorkExperience1;
    private javax.swing.JLabel lblPhoneNumber;
    private javax.swing.JLabel lblPhoneNumber1;
    private javax.swing.JLabel lblPhoneNumber2;
    private javax.swing.JLabel lblRestaurantInfo;
    private javax.swing.JLabel lblRestaurantName;
    private javax.swing.JLabel lblRestaurantName1;
    private javax.swing.JLabel lblRestaurantName2;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtDoctorID;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtExperience;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtPhoneNumber;
    private javax.swing.JTextField txtSpecialist;
    private javax.swing.JTextField txtUsername;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
