/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface.Doctor;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.PatientBills;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daddy
 */
public class DoctorVisitJPanel extends javax.swing.JPanel {

    /**
     * Creates new form DoctorVisitJPanel
     */
    private JPanel userProCont;
    private Ecosystem ecoSystem;
    private User userAcc;
    private Patient pat;

    public DoctorVisitJPanel(JPanel userProcessContainer, User account, Ecosystem ecoSystem, Patient patient) {
        initComponents();
        this.userProCont = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.userAcc = account;
        this.pat = patient;
        populateBillTable();
    }

    private void populateBillTable() {
        DefaultTableModel model = (DefaultTableModel) BillTable.getModel();

        model.setRowCount(0);

        for (PatientBills b : pat.getpBills()) {

            Object[] row = new Object[7];
            row[0] = b.getName();
            row[1] = b.getOrgType();
            row[2] = b.getAmount();
            row[3] = b.getStatus();
            row[4] = b.getResult();
            
            model.addRow(row);

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        BillTable = new javax.swing.JTable();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        requestLabTestsBtn = new javax.swing.JButton();
        requestMedBtn = new javax.swing.JButton();
        requestBloodBtn = new javax.swing.JButton();
        readyToDischargeBtn = new javax.swing.JButton();
        endVisitBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 102, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BillTable.setBackground(new java.awt.Color(204, 255, 204));
        BillTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 255, 102)));
        BillTable.setFont(new java.awt.Font("Futura", 1, 14)); // NOI18N
        BillTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Item Name", "Organization", "Amount", "Status", "Result"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(BillTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 1420, 191));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 1402, 10));

        jLabel1.setBackground(new java.awt.Color(0, 153, 204));
        jLabel1.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient History");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 420, 50));

        requestLabTestsBtn.setBackground(new java.awt.Color(204, 255, 204));
        requestLabTestsBtn.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        requestLabTestsBtn.setForeground(new java.awt.Color(0, 102, 102));
        requestLabTestsBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/lab.png"))); // NOI18N
        requestLabTestsBtn.setText("Request Lab Tests");
        requestLabTestsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestLabTestsBtnActionPerformed(evt);
            }
        });
        add(requestLabTestsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 370, 250, 60));

        requestMedBtn.setBackground(new java.awt.Color(204, 255, 204));
        requestMedBtn.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        requestMedBtn.setForeground(new java.awt.Color(0, 102, 102));
        requestMedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/medicine.png"))); // NOI18N
        requestMedBtn.setText("Request Medicines");
        requestMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestMedBtnActionPerformed(evt);
            }
        });
        add(requestMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 370, 250, 60));

        requestBloodBtn.setBackground(new java.awt.Color(204, 255, 204));
        requestBloodBtn.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        requestBloodBtn.setForeground(new java.awt.Color(0, 102, 102));
        requestBloodBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/blood-test.png"))); // NOI18N
        requestBloodBtn.setText("Request Blood");
        requestBloodBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                requestBloodBtnActionPerformed(evt);
            }
        });
        add(requestBloodBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 370, 230, 60));

        readyToDischargeBtn.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        readyToDischargeBtn.setForeground(new java.awt.Color(255, 0, 0));
        readyToDischargeBtn.setText("Ready to Discharge");
        readyToDischargeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readyToDischargeBtnActionPerformed(evt);
            }
        });
        add(readyToDischargeBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 380, 220, 50));

        endVisitBtn.setBackground(new java.awt.Color(255, 0, 0));
        endVisitBtn.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        endVisitBtn.setForeground(new java.awt.Color(255, 255, 255));
        endVisitBtn.setText("End Visit");
        endVisitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endVisitBtnActionPerformed(evt);
            }
        });
        add(endVisitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(910, 450, 120, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/phistory.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void requestLabTestsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestLabTestsBtnActionPerformed
        // TODO add your handling code here:

        DoctorRequestLabTestJPanel doctorRequestLabTestJPanel = new DoctorRequestLabTestJPanel(userProCont, userAcc, ecoSystem, pat);
        userProCont.add("Request Lab Tests", doctorRequestLabTestJPanel);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);

    }//GEN-LAST:event_requestLabTestsBtnActionPerformed

    private void requestMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestMedBtnActionPerformed
        // TODO add your handling code here:

        DoctorRequestMedicineJPanel doctorRequestMedicineJPanel = new DoctorRequestMedicineJPanel(userProCont, userAcc, ecoSystem, pat);
        userProCont.add("Request  Medicine", doctorRequestMedicineJPanel);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);

    }//GEN-LAST:event_requestMedBtnActionPerformed

    private void requestBloodBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_requestBloodBtnActionPerformed
        // TODO add your handling code here:

        DoctorRequestBloodJPanel doctorRequestBloodJPanel = new DoctorRequestBloodJPanel(userProCont, userAcc, ecoSystem, pat);
        userProCont.add("Request Blood", doctorRequestBloodJPanel);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_requestBloodBtnActionPerformed

    private void readyToDischargeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readyToDischargeBtnActionPerformed
        // TODO add your handling code here:
        pat.setpStatus("Ready to Discharge");
        DoctorWorkAreaJPanel doctor = new DoctorWorkAreaJPanel(userProCont,userAcc,ecoSystem);
        userProCont.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_readyToDischargeBtnActionPerformed

    private void endVisitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endVisitBtnActionPerformed
        // TODO add your handling code here:
        pat.setpStatus("Under Observation");
        DoctorWorkAreaJPanel doctor = new DoctorWorkAreaJPanel(userProCont,userAcc,ecoSystem);
        userProCont.add("Request Blood", doctor);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_endVisitBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BillTable;
    private javax.swing.JButton endVisitBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton readyToDischargeBtn;
    private javax.swing.JButton requestBloodBtn;
    private javax.swing.JButton requestLabTestsBtn;
    private javax.swing.JButton requestMedBtn;
    // End of variables declaration//GEN-END:variables
}
