/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface.ReceptionRole;


import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.Roles.RolePatient;
import BusinessModel.UserAccount.User;
import BusinessUtil.Mail.SendMail;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author indian
 */
public class CreatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientPanel
     */
    private final JPanel userProCont;

    private final Ecosystem ecoSystem;
    User userAcc;
    String selectImgPath;
    Boolean IsconcentFormSigned;

    public CreatePatientJPanel(JPanel userProcessContainer, Ecosystem system, User user) {

        initComponents();
        this.userAcc = user;
        this.userProCont = userProcessContainer;
        this.ecoSystem = system;
        selectImgPath = "";
        IsconcentFormSigned = false;

        genderDropDown.removeAllItems();
        genderDropDown.addItem("Male");
        genderDropDown.addItem("Female");
        genderDropDown.addItem("Other");

        bloodGrpDropDown.removeAllItems();
        bloodGrpDropDown.addItem("A+");
        bloodGrpDropDown.addItem("A-");
        bloodGrpDropDown.addItem("B+");
        bloodGrpDropDown.addItem("B-");
        bloodGrpDropDown.addItem("O+");
        bloodGrpDropDown.addItem("O-");
        bloodGrpDropDown.addItem("AB+");
        bloodGrpDropDown.addItem("AB-");
        Date today = new Date();
        birthdayBox.setDate(today);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientFirstName = new javax.swing.JLabel();
        lblRestaurantInfo = new javax.swing.JLabel();
        fNameTxt = new javax.swing.JTextField();
        lblPatientLastName = new javax.swing.JLabel();
        lNameTxt = new javax.swing.JTextField();
        lblPatientGender = new javax.swing.JLabel();
        lblPatientHealthInsuranceID = new javax.swing.JLabel();
        insuranceTxt = new javax.swing.JTextField();
        lblPatientAddress = new javax.swing.JLabel();
        patAddressTxt = new javax.swing.JTextField();
        lblPatientPhone = new javax.swing.JLabel();
        mobileTxt = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        lblAddress4 = new javax.swing.JLabel();
        injuryTxt = new javax.swing.JTextField();
        lblPhoneNumber4 = new javax.swing.JLabel();
        lblRestaurantName4 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        submitBtn = new javax.swing.JButton();
        lblRestaurantName5 = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JTextField();
        cashRBtn = new javax.swing.JRadioButton();
        insuranceRBtn = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JButton();
        lblPhotoImage = new javax.swing.JLabel();
        lblPaymentMethod = new javax.swing.JLabel();
        genderDropDown = new javax.swing.JComboBox<>();
        bloodGrpDropDown = new javax.swing.JComboBox<>();
        lblAccidentLocation = new javax.swing.JLabel();
        accidentLocTxt = new javax.swing.JTextField();
        lblPhoto = new javax.swing.JLabel();
        lblErrorFname = new javax.swing.JLabel();
        lblErrorLname = new javax.swing.JLabel();
        lblErrorHId = new javax.swing.JLabel();
        lblErrorPhone = new javax.swing.JLabel();
        lblErrorAddress = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorInjury = new javax.swing.JLabel();
        lblErrorUserName = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        lblErrorAccidentLocation = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        backBtn = new javax.swing.JButton();
        lblPaymentMethod1 = new javax.swing.JLabel();
        birthdayBox = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(204, 0, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatientFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setText("First Name");
        add(lblPatientFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 180, -1, -1));

        lblRestaurantInfo.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantInfo.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        lblRestaurantInfo.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantInfo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurantInfo.setText("Create Patient");
        add(lblRestaurantInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, 260, 80));

        fNameTxt.setBackground(new java.awt.Color(255, 204, 255));
        fNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxtKeyReleased(evt);
            }
        });
        add(fNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 110, 40));

        lblPatientLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setText("Last Name");
        add(lblPatientLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 230, -1, -1));

        lNameTxt.setBackground(new java.awt.Color(255, 204, 255));
        lNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtActionPerformed(evt);
            }
        });
        lNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxtKeyReleased(evt);
            }
        });
        add(lNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 110, 40));

        lblPatientGender.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientGender.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientGender.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientGender.setText("Sex");
        add(lblPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 290, -1, -1));

        lblPatientHealthInsuranceID.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientHealthInsuranceID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientHealthInsuranceID.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientHealthInsuranceID.setText("Insurance Id");
        add(lblPatientHealthInsuranceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 440, -1, -1));

        insuranceTxt.setBackground(new java.awt.Color(255, 204, 255));
        insuranceTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceTxtActionPerformed(evt);
            }
        });
        insuranceTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                insuranceTxtKeyReleased(evt);
            }
        });
        add(insuranceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 440, 110, 40));

        lblPatientAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientAddress.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientAddress.setText("Patient address");
        add(lblPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 300, 140, 20));

        patAddressTxt.setBackground(new java.awt.Color(255, 204, 255));
        patAddressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                patAddressTxtActionPerformed(evt);
            }
        });
        patAddressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                patAddressTxtKeyReleased(evt);
            }
        });
        add(patAddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 290, 130, 40));

        lblPatientPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientPhone.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientPhone.setText("Mobile Number");
        add(lblPatientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        mobileTxt.setBackground(new java.awt.Color(255, 204, 255));
        mobileTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobileTxtActionPerformed(evt);
            }
        });
        mobileTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobileTxtKeyReleased(evt);
            }
        });
        add(mobileTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 230, 130, 40));

        lblDOB.setBackground(new java.awt.Color(255, 255, 255));
        lblDOB.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblDOB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDOB.setText("Date of Birth");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, -1, 40));

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email address");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 180, -1, -1));

        emailTxt.setBackground(new java.awt.Color(255, 204, 255));
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTxtKeyReleased(evt);
            }
        });
        add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 170, 130, 40));

        lblAddress4.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAddress4.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddress4.setText("Blood Type");
        add(lblAddress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 390, 116, -1));

        injuryTxt.setBackground(new java.awt.Color(255, 204, 255));
        injuryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injuryTxtActionPerformed(evt);
            }
        });
        injuryTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                injuryTxtKeyReleased(evt);
            }
        });
        add(injuryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 500, 150, 40));

        lblPhoneNumber4.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPhoneNumber4.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber4.setText("Injury Type");
        add(lblPhoneNumber4, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 510, -1, -1));

        lblRestaurantName4.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantName4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        lblRestaurantName4.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName4.setText("UserName");
        add(lblRestaurantName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 170, -1, -1));

        userNameTxt.setBackground(new java.awt.Color(255, 204, 255));
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        userNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameTxtKeyReleased(evt);
            }
        });
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 210, 150, 40));

        submitBtn.setBackground(new java.awt.Color(0, 51, 255));
        submitBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(255, 255, 255));
        submitBtn.setText("Submit");
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 490, 159, 46));

        lblRestaurantName5.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantName5.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        lblRestaurantName5.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName5.setText("Password");
        add(lblRestaurantName5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 300, -1, -1));

        passwordTxt.setBackground(new java.awt.Color(255, 204, 255));
        passwordTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                passwordTxtKeyReleased(evt);
            }
        });
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 340, 150, 40));

        cashRBtn.setBackground(new java.awt.Color(255, 204, 255));
        cashRBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        cashRBtn.setForeground(new java.awt.Color(255, 255, 255));
        cashRBtn.setText("Cash Payment");
        cashRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRBtnActionPerformed(evt);
            }
        });
        add(cashRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, -1, -1));

        insuranceRBtn.setBackground(new java.awt.Color(255, 204, 255));
        insuranceRBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        insuranceRBtn.setForeground(new java.awt.Color(255, 255, 255));
        insuranceRBtn.setText("Insurance ");
        insuranceRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceRBtnActionPerformed(evt);
            }
        });
        add(insuranceRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, -1));

        searchBtn.setBackground(new java.awt.Color(0, 51, 255));
        searchBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Browse");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 550, 100, 40));
        add(lblPhotoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 160, 140));

        lblPaymentMethod.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentMethod.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        lblPaymentMethod.setForeground(new java.awt.Color(255, 255, 255));
        lblPaymentMethod.setText("Login Credentials");
        add(lblPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 100, -1, -1));

        genderDropDown.setBackground(new java.awt.Color(255, 204, 255));
        genderDropDown.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        genderDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genderDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderDropDownActionPerformed(evt);
            }
        });
        add(genderDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 290, 92, 30));

        bloodGrpDropDown.setBackground(new java.awt.Color(255, 204, 255));
        bloodGrpDropDown.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        bloodGrpDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bloodGrpDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGrpDropDownActionPerformed(evt);
            }
        });
        add(bloodGrpDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 110, 40));

        lblAccidentLocation.setBackground(new java.awt.Color(255, 255, 255));
        lblAccidentLocation.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAccidentLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblAccidentLocation.setText("Accident Location");
        add(lblAccidentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 440, -1, 25));

        accidentLocTxt.setBackground(new java.awt.Color(255, 204, 255));
        accidentLocTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                accidentLocTxtKeyReleased(evt);
            }
        });
        add(accidentLocTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 430, 150, 40));

        lblPhoto.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoto.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPhoto.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoto.setText("Photo");
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        lblErrorFname.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorFname.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 110, 30));

        lblErrorLname.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorLname.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 560, 100, 30));

        lblErrorHId.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorHId.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorHId, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 470, 124, 21));

        lblErrorPhone.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorPhone.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 600, 135, 20));

        lblErrorAddress.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorAddress.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 550, 130, 21));

        lblErrorEmail.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorEmail.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 270, 129, 22));

        lblErrorInjury.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorInjury.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorInjury, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 430, 140, 22));

        lblErrorUserName.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorUserName.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 270, 200, 26));

        lblErrorPassword.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorPassword.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 410, 200, 26));

        lblErrorAccidentLocation.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorAccidentLocation.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorAccidentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 116, 22));

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Accident Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 210, 34));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Personal Details");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 230, 31));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Contact Details");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 100, 190, 31));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator3.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jSeparator4.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, 1434, 5));

        backBtn.setBackground(new java.awt.Color(0, 51, 255));
        backBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 90, 30));

        lblPaymentMethod1.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentMethod1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPaymentMethod1.setForeground(new java.awt.Color(255, 255, 255));
        lblPaymentMethod1.setText("Payment Method");
        add(lblPaymentMethod1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 100, -1, -1));

        birthdayBox.setBackground(new java.awt.Color(255, 204, 255));
        birthdayBox.setDateFormatString("MM-dd-yyyy");
        birthdayBox.setMaxSelectableDate(new Date());
        add(birthdayBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 340, 110, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/icons8-patient-50.png"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, -1, -1));

        jSeparator5.setBackground(new java.awt.Color(0, 0, 0));
        add(jSeparator5, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 420, 470, 10));
    }// </editor-fold>//GEN-END:initComponents

    private void lNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtActionPerformed

    private void insuranceTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceTxtActionPerformed

    private void patAddressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_patAddressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_patAddressTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void injuryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injuryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_injuryTxtActionPerformed

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed
        // TODO add your handling code here:
        if (ecoSystem.getUserAccountDirectory().checkIfUsernameIsUnique(userNameTxt.getText())
                && (lblErrorFname.getText() == null || lblErrorFname.getText().equals(""))
                && (lblErrorLname.getText() == null || lblErrorLname.getText().equals(""))
                && (lblErrorAddress.getText() == null || lblErrorAddress.getText().equals(""))
                && (lblErrorEmail.getText() == null || lblErrorEmail.getText().equals(""))
                && (lblErrorHId.getText() == null || lblErrorHId.getText().equals(""))
                && (lblErrorInjury.getText() == null || lblErrorInjury.getText().equals(""))
                && (lblErrorPassword.getText() == null || lblErrorPassword.getText().equals(""))
                && (lblErrorPhone.getText() == null || lblErrorPhone.getText().equals(""))
                && (lblErrorUserName.getText() == null || lblErrorUserName.getText().equals(""))) {
            Patient patient = new Patient(userNameTxt.getText());

            patient.setpFirstName(fNameTxt.getText());
            patient.setpLastName(lNameTxt.getText());
            patient.setpAge(CalculateAge(birthdayBox.getDate(), java.util.Calendar.getInstance().getTime()));
            patient.setpGender((String) genderDropDown.getSelectedItem());
            patient.setpHealthInsuranceID(insuranceTxt.getText());
            patient.setpAddress(patAddressTxt.getText());
            patient.setpPhoneNo(mobileTxt.getText());
            patient.setpEmailAddress(emailTxt.getText());
            patient.setPdob(birthdayBox.getDate());
            patient.setpInjuryType(injuryTxt.getText());
            patient.setpAccidentLocation(accidentLocTxt.getText());
            patient.setpBloodType((String) bloodGrpDropDown.getSelectedItem());
            patient.setpBloodBankStatus("New Patient");
            patient.setpPharmaStatus("New Patient");
            patient.setpLabStatus("New Patient");
            patient.setpStatus("New Patient");
            patient.setpUserName(userNameTxt.getText());
            patient.setpImageUrl(selectImgPath);
            patient.setpIsConcentFormSigned(IsconcentFormSigned);
            patient.setpDateOfAdmit(java.util.Calendar.getInstance().getTime());
            if (insuranceRBtn.isSelected()) {
                patient.setpInsuranceStatus("Insurance");
            } else {
                patient.setpInsuranceStatus("Cash");
            }

            ecoSystem.getUserAccountDirectory().createUser(userNameTxt.getText(), passwordTxt.getText(), null, new RolePatient());
            ecoSystem.getPatientDirect().createPatient(patient);
            SendMail.sendMail(patient.getpEmailAddress(), "Hello "+patient.getpFirstName()+", your account has been successfully created in Hospital EcoSystem Management!");
            for (Patient p : ecoSystem.getPatientDirect().getPatientList()) {
                if (p.getpUserName().equals(userNameTxt.getText())) {
                    ecoSystem.getPatientDirect().AddBill(p, "Bed Charge", "Hospital", "Ammount");
                }
            }

            JOptionPane.showMessageDialog(null, "Patient Created");
            
            System.out.println("existing patients in the portal ---");
            for (Patient p : ecoSystem.getPatientDirect().getPatientList()) {
                System.out.println("patient---"+p.getpFirstName());
            }

            ReceptionWorkAreaJPanel receptionWorkAreaJPanel = new ReceptionWorkAreaJPanel(userProCont, userAcc, ecoSystem);
            userProCont.add("Reception Work Area", receptionWorkAreaJPanel);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);

        } else {
            JOptionPane.showMessageDialog(null, "Invalid details");
        }


    }//GEN-LAST:event_submitBtnActionPerformed

    public int CalculateAge(Date birthDate, Date currentDate) {
        // validate inputs ...                                                                               
        DateFormat formatter = new SimpleDateFormat("yyyyMMdd");
        int d1 = Integer.parseInt(formatter.format(birthDate));
        int d2 = Integer.parseInt(formatter.format(currentDate));
        int age = (d2 - d1) / 10000;
        return age;
    }

    private void cashRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRBtnActionPerformed
        // TODO add your handling code here:
        cashRBtn.setSelected(true);
        insuranceRBtn.setSelected(false);
    }//GEN-LAST:event_cashRBtnActionPerformed

    private void insuranceRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceRBtnActionPerformed
        // TODO add your handling code here:
        cashRBtn.setSelected(false);
        insuranceRBtn.setSelected(true);
    }//GEN-LAST:event_insuranceRBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            selectImgPath = selectedImagePath;

            ImageIcon ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblPhotoImage.getWidth(), lblPhotoImage.getHeight(), Image.SCALE_SMOOTH);
            lblPhotoImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void genderDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderDropDownActionPerformed

    private void bloodGrpDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGrpDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGrpDropDownActionPerformed

    private void fNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(fNameTxt.getText());
        if (!match.matches()) {
            lblErrorFname.setText("Invalid!");
        } else {
            lblErrorFname.setText(null);
        }


    }//GEN-LAST:event_fNameTxtKeyReleased

    private void lNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(lNameTxt.getText());
        if (!match.matches()) {
            lblErrorLname.setText("Invalid!");
        } else {
            lblErrorLname.setText(null);
        }

    }//GEN-LAST:event_lNameTxtKeyReleased

    private void insuranceTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insuranceTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(insuranceTxt.getText());
        if (!match.matches()) {
            lblErrorHId.setText("Invalid!");
        } else {
            lblErrorHId.setText(null);
        }

    }//GEN-LAST:event_insuranceTxtKeyReleased

    private void patAddressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_patAddressTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z0-9 ,'/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(patAddressTxt.getText());
        if (!match.matches()) {
            lblErrorAddress.setText("Invalid!");
        } else {
            lblErrorAddress.setText(null);
        }


    }//GEN-LAST:event_patAddressTxtKeyReleased

    private void mobileTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobileTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[0-9 +()-]{10,18}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(mobileTxt.getText());
        if (!match.matches()) {
            lblErrorPhone.setText("Invalid!");
        } else {
            lblErrorPhone.setText(null);
        }

    }//GEN-LAST:event_mobileTxtKeyReleased

    private void emailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(emailTxt.getText());
        if (!match.matches()) {
            lblErrorEmail.setText("Invalid!");
        } else {
            lblErrorEmail.setText(null);
        }

    }//GEN-LAST:event_emailTxtKeyReleased

    private void accidentLocTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_accidentLocTxtKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_accidentLocTxtKeyReleased

    private void injuryTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_injuryTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(injuryTxt.getText());
        if (!match.matches()) {
            lblErrorInjury.setText("Invalid!");
        } else {
            lblErrorInjury.setText(null);
        }

    }//GEN-LAST:event_injuryTxtKeyReleased

    private void userNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(userNameTxt.getText());
        if (!match.matches()) {
            lblErrorUserName.setText("Invalid!");
        } else {
            lblErrorUserName.setText(null);
        }

    }//GEN-LAST:event_userNameTxtKeyReleased

    private void passwordTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_passwordTxtKeyReleased
        // TODO add your handling code here:

        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(passwordTxt.getText());
        if (!match.matches()) {
            lblErrorPassword.setText("Invalid!");
        } else {
            lblErrorPassword.setText(null);
        }

    }//GEN-LAST:event_passwordTxtKeyReleased

    private void mobileTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobileTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobileTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ReceptionWorkAreaJPanel patientBillJPanel = new ReceptionWorkAreaJPanel(userProCont,userAcc,ecoSystem);
        userProCont.add("Patient Bill", patientBillJPanel);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);
    }//GEN-LAST:event_backBtnActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accidentLocTxt;
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser birthdayBox;
    private javax.swing.JComboBox<String> bloodGrpDropDown;
    private javax.swing.JRadioButton cashRBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JComboBox<String> genderDropDown;
    private javax.swing.JTextField injuryTxt;
    private javax.swing.JRadioButton insuranceRBtn;
    private javax.swing.JTextField insuranceTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField lNameTxt;
    private javax.swing.JLabel lblAccidentLocation;
    private javax.swing.JLabel lblAddress4;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorAccidentLocation;
    private javax.swing.JLabel lblErrorAddress;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorFname;
    private javax.swing.JLabel lblErrorHId;
    private javax.swing.JLabel lblErrorInjury;
    private javax.swing.JLabel lblErrorLname;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorPhone;
    private javax.swing.JLabel lblErrorUserName;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientHealthInsuranceID;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JLabel lblPaymentMethod1;
    private javax.swing.JLabel lblPhoneNumber4;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoImage;
    private javax.swing.JLabel lblRestaurantInfo;
    private javax.swing.JLabel lblRestaurantName4;
    private javax.swing.JLabel lblRestaurantName5;
    private javax.swing.JTextField mobileTxt;
    private javax.swing.JTextField passwordTxt;
    private javax.swing.JTextField patAddressTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
