/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface.ReceptionRole;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import java.awt.Image;
import java.io.File;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author indian
 */
public class UpdatePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePatientPanel
     */
    private final JPanel userProCont;
    private final Ecosystem ecoSystem;
    User userAcc;
    Patient patient;

    public UpdatePatientJPanel(JPanel userProcessContainer, Ecosystem system, User user, Patient patient) {
        initComponents();
        this.userAcc = user;
        this.userProCont = userProcessContainer;
        this.ecoSystem = system;
        this.patient = patient;

        GenderDropDownList.removeAllItems();
        GenderDropDownList.addItem("Male");
        GenderDropDownList.addItem("Female");
        GenderDropDownList.addItem("Other");

        bloodGrpDropDown.removeAllItems();
        bloodGrpDropDown.addItem("A+");
        bloodGrpDropDown.addItem("A-");
        bloodGrpDropDown.addItem("B+");
        bloodGrpDropDown.addItem("B-");
        bloodGrpDropDown.addItem("O+");
        bloodGrpDropDown.addItem("O-");
        bloodGrpDropDown.addItem("AB+");
        bloodGrpDropDown.addItem("AB-");

        addressTxt.setText(patient.getpAddress());
        bloodGrpDropDown.setSelectedItem(patient.getpBloodType());
        birthDateBox.setDate(patient.getPdob());
        emailTxt.setText(patient.getpEmailAddress());
        fNameTxt.setText(patient.getpFirstName());
        GenderDropDownList.setSelectedItem(patient.getpGender());
        insuranceIdTxt.setText(patient.getpHealthInsuranceID());
        injuryTxt.setText(patient.getpInjuryType());
        lNameTxt.setText(patient.getpLastName());
        mobiletTxt.setText(patient.getpPhoneNo());
        userNameTxt.setText(patient.getpUserName());
        accidentLocTxt.setText(patient.getpAccidentLocation());
        if (patient.getpInsuranceStatus() != null) {
            if (patient.getpInsuranceStatus().equals("Insurance")) {
                insuranceRBtn.setSelected(true);
                cashRBtn.setSelected(false);
            } else {
                cashRBtn.setSelected(true);
                insuranceRBtn.setSelected(false);
            }
        }
        ImageIcon ii = new ImageIcon(patient.getpImageUrl());
        Image image = ii.getImage().getScaledInstance(130, 130, Image.SCALE_SMOOTH);
        lblPhotoImage.setIcon(new ImageIcon(image));

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblPatientFirstName = new javax.swing.JLabel();
        lblUpdatePatient = new javax.swing.JLabel();
        fNameTxt = new javax.swing.JTextField();
        lblPatientLastName = new javax.swing.JLabel();
        lNameTxt = new javax.swing.JTextField();
        lblPatientGender = new javax.swing.JLabel();
        lblPatientHealthInsuranceID = new javax.swing.JLabel();
        insuranceIdTxt = new javax.swing.JTextField();
        lblPatientAddress = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        lblPatientPhone = new javax.swing.JLabel();
        mobiletTxt = new javax.swing.JTextField();
        lblDOB = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        emailTxt = new javax.swing.JTextField();
        lblAddress4 = new javax.swing.JLabel();
        injuryTxt = new javax.swing.JTextField();
        lblPhoneNumber4 = new javax.swing.JLabel();
        lblRestaurantName4 = new javax.swing.JLabel();
        userNameTxt = new javax.swing.JTextField();
        updateBtn = new javax.swing.JButton();
        cashRBtn = new javax.swing.JRadioButton();
        insuranceRBtn = new javax.swing.JRadioButton();
        searchBtn = new javax.swing.JButton();
        lblPhotoImage = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        lblPaymentMethod = new javax.swing.JLabel();
        GenderDropDownList = new javax.swing.JComboBox<>();
        bloodGrpDropDown = new javax.swing.JComboBox<>();
        lblAccidentLocation = new javax.swing.JLabel();
        accidentLocTxt = new javax.swing.JTextField();
        birthDateBox = new com.toedter.calendar.JDateChooser();
        lblErrorLname = new javax.swing.JLabel();
        lblErrorFname = new javax.swing.JLabel();
        lblErrorHId = new javax.swing.JLabel();
        lblErrorPhone = new javax.swing.JLabel();
        lblErrorAddress = new javax.swing.JLabel();
        lblErrorEmail = new javax.swing.JLabel();
        lblErrorInjury = new javax.swing.JLabel();
        lblErrorUserName = new javax.swing.JLabel();
        lblErrorAccidentLocation = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        backBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 0, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblPatientFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setText("First Name");
        add(lblPatientFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, -1, -1));

        lblUpdatePatient.setBackground(new java.awt.Color(255, 255, 255));
        lblUpdatePatient.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        lblUpdatePatient.setForeground(new java.awt.Color(255, 255, 255));
        lblUpdatePatient.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUpdatePatient.setText("Update Patient Details");
        add(lblUpdatePatient, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 20, 280, 50));

        fNameTxt.setBackground(new java.awt.Color(255, 204, 255));
        fNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fNameTxtActionPerformed(evt);
            }
        });
        fNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fNameTxtKeyReleased(evt);
            }
        });
        add(fNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 140, 190, 40));

        lblPatientLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setText("Last Name");
        add(lblPatientLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, 30));

        lNameTxt.setBackground(new java.awt.Color(255, 204, 255));
        lNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtActionPerformed(evt);
            }
        });
        lNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lNameTxtKeyReleased(evt);
            }
        });
        add(lNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 260, 190, 40));

        lblPatientGender.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientGender.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientGender.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientGender.setText("Gender");
        add(lblPatientGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, -1, -1));

        lblPatientHealthInsuranceID.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientHealthInsuranceID.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientHealthInsuranceID.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientHealthInsuranceID.setText("Insurance Id");
        add(lblPatientHealthInsuranceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 150, -1, -1));

        insuranceIdTxt.setBackground(new java.awt.Color(255, 204, 255));
        insuranceIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceIdTxtActionPerformed(evt);
            }
        });
        insuranceIdTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                insuranceIdTxtKeyReleased(evt);
            }
        });
        add(insuranceIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, 190, 40));

        lblPatientAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientAddress.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientAddress.setText("Address");
        add(lblPatientAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 440, 90, 40));

        addressTxt.setBackground(new java.awt.Color(255, 204, 255));
        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        addressTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                addressTxtKeyReleased(evt);
            }
        });
        add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 440, 190, 40));

        lblPatientPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientPhone.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPatientPhone.setText("Mobile Number");
        add(lblPatientPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 390, -1, 30));

        mobiletTxt.setBackground(new java.awt.Color(255, 204, 255));
        mobiletTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mobiletTxtActionPerformed(evt);
            }
        });
        mobiletTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                mobiletTxtKeyReleased(evt);
            }
        });
        add(mobiletTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 380, 190, 40));

        lblDOB.setBackground(new java.awt.Color(255, 255, 255));
        lblDOB.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblDOB.setForeground(new java.awt.Color(255, 255, 255));
        lblDOB.setText("Date of Birth");
        add(lblDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        lblEmail.setBackground(new java.awt.Color(255, 255, 255));
        lblEmail.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email Address");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, 30));

        emailTxt.setBackground(new java.awt.Color(255, 204, 255));
        emailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailTxtActionPerformed(evt);
            }
        });
        emailTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                emailTxtKeyReleased(evt);
            }
        });
        add(emailTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 190, 40));

        lblAddress4.setBackground(new java.awt.Color(255, 255, 255));
        lblAddress4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAddress4.setForeground(new java.awt.Color(255, 255, 255));
        lblAddress4.setText("Blood Group");
        add(lblAddress4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        injuryTxt.setBackground(new java.awt.Color(255, 204, 255));
        injuryTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                injuryTxtActionPerformed(evt);
            }
        });
        injuryTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                injuryTxtKeyReleased(evt);
            }
        });
        add(injuryTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 270, 190, 40));

        lblPhoneNumber4.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPhoneNumber4.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoneNumber4.setText("Injury Type");
        add(lblPhoneNumber4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 280, -1, -1));

        lblRestaurantName4.setBackground(new java.awt.Color(255, 255, 255));
        lblRestaurantName4.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblRestaurantName4.setForeground(new java.awt.Color(255, 255, 255));
        lblRestaurantName4.setText("UserName");
        add(lblRestaurantName4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 335, -1, 40));

        userNameTxt.setEditable(false);
        userNameTxt.setBackground(new java.awt.Color(255, 204, 255));
        userNameTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                userNameTxtKeyReleased(evt);
            }
        });
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 330, 190, 40));

        updateBtn.setBackground(new java.awt.Color(0, 51, 204));
        updateBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1040, 420, 110, 30));

        cashRBtn.setBackground(new java.awt.Color(255, 204, 255));
        cashRBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        cashRBtn.setText("Cash ");
        cashRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cashRBtnActionPerformed(evt);
            }
        });
        add(cashRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 400, -1, -1));

        insuranceRBtn.setBackground(new java.awt.Color(255, 204, 255));
        insuranceRBtn.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        insuranceRBtn.setText("Insurance ");
        insuranceRBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceRBtnActionPerformed(evt);
            }
        });
        add(insuranceRBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 400, -1, -1));

        searchBtn.setBackground(new java.awt.Color(0, 51, 255));
        searchBtn.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        searchBtn.setForeground(new java.awt.Color(255, 255, 255));
        searchBtn.setText("Browse");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 170, -1, 40));
        add(lblPhotoImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 230, 170, 160));

        lblPhoto.setBackground(new java.awt.Color(255, 255, 255));
        lblPhoto.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPhoto.setForeground(new java.awt.Color(255, 255, 255));
        lblPhoto.setText("Picture");
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 130, -1, -1));

        lblPaymentMethod.setBackground(new java.awt.Color(255, 255, 255));
        lblPaymentMethod.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPaymentMethod.setForeground(new java.awt.Color(255, 255, 255));
        lblPaymentMethod.setText("Payment ");
        add(lblPaymentMethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, -1, -1));

        GenderDropDownList.setBackground(new java.awt.Color(255, 204, 255));
        GenderDropDownList.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        GenderDropDownList.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GenderDropDownListActionPerformed(evt);
            }
        });
        add(GenderDropDownList, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 320, 190, 40));

        bloodGrpDropDown.setBackground(new java.awt.Color(255, 204, 255));
        bloodGrpDropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        bloodGrpDropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloodGrpDropDownActionPerformed(evt);
            }
        });
        add(bloodGrpDropDown, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 450, 180, 30));

        lblAccidentLocation.setBackground(new java.awt.Color(255, 255, 255));
        lblAccidentLocation.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblAccidentLocation.setForeground(new java.awt.Color(255, 255, 255));
        lblAccidentLocation.setText("Accident Location");
        add(lblAccidentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, -1, -1));

        accidentLocTxt.setBackground(new java.awt.Color(255, 204, 255));
        accidentLocTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accidentLocTxtActionPerformed(evt);
            }
        });
        add(accidentLocTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 210, 190, 40));

        birthDateBox.setBackground(new java.awt.Color(255, 204, 255));
        add(birthDateBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 510, 190, 40));

        lblErrorLname.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorLname.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorLname, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 150, 26));

        lblErrorFname.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorFname.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorFname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 150, 26));

        lblErrorHId.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorHId.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorHId, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 200, 146, 26));

        lblErrorPhone.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorPhone.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 280, 150, 26));

        lblErrorAddress.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorAddress.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 370, 148, 26));

        lblErrorEmail.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorEmail.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 560, 150, 26));

        lblErrorInjury.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorInjury.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorInjury, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 380, 150, 26));

        lblErrorUserName.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorUserName.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 540, 150, 26));

        lblErrorAccidentLocation.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblErrorAccidentLocation.setForeground(new java.awt.Color(255, 51, 51));
        add(lblErrorAccidentLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 360, 130, 26));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 1300, 10));

        backBtn.setBackground(new java.awt.Color(0, 51, 255));
        backBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/icons8-patient-50.png"))); // NOI18N
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 60, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void lNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtActionPerformed

    private void insuranceIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceIdTxtActionPerformed

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void emailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailTxtActionPerformed

    private void injuryTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_injuryTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_injuryTxtActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        if ((lblErrorFname.getText() == null || lblErrorFname.getText().equals(""))
                && (lblErrorLname.getText() == null || lblErrorLname.getText().equals(""))
                && (lblErrorAddress.getText() == null || lblErrorAddress.getText().equals(""))
                && (lblErrorEmail.getText() == null || lblErrorEmail.getText().equals(""))
                && (lblErrorHId.getText() == null || lblErrorHId.getText().equals(""))
                && (lblErrorInjury.getText() == null || lblErrorInjury.getText().equals(""))
                && (lblErrorPhone.getText() == null || lblErrorPhone.getText().equals(""))
                && (lblErrorUserName.getText() == null || lblErrorUserName.getText().equals(""))) {
            patient.setpFirstName(fNameTxt.getText());
            patient.setpLastName(lNameTxt.getText());
            patient.setpAge(CalculateAge(birthDateBox.getDate(), java.util.Calendar.getInstance().getTime()));
            patient.setpGender((String) GenderDropDownList.getSelectedItem());
            patient.setpHealthInsuranceID(insuranceIdTxt.getText());
            patient.setpAddress(addressTxt.getText());
            patient.setpPhoneNo(mobiletTxt.getText());
            patient.setpEmailAddress(emailTxt.getText());
            patient.setPdob(birthDateBox.getDate());
            patient.setpInjuryType(injuryTxt.getText());
            patient.setpBloodType((String) bloodGrpDropDown.getSelectedItem());
            patient.setpUserName(userNameTxt.getText());
            patient.setpAccidentLocation(accidentLocTxt.getText());
            if (insuranceRBtn.isSelected()) {
                patient.setpInsuranceStatus("Insurance");
            } else {
                patient.setpInsuranceStatus("Cash");
            }
            JOptionPane.showMessageDialog(null, "Update Complete.");

            ReceptionWorkAreaJPanel receptionWorkAreaJPanel = new ReceptionWorkAreaJPanel(userProCont, userAcc, ecoSystem);
            userProCont.add("Reception Work Area", receptionWorkAreaJPanel);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);
        }
        else
        {
             JOptionPane.showMessageDialog(null, "Username is not Unique and Please Fill Correct Details");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void cashRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cashRBtnActionPerformed
        // TODO add your handling code here:
        cashRBtn.setSelected(true);
        insuranceRBtn.setSelected(false);
    }//GEN-LAST:event_cashRBtnActionPerformed

    private void insuranceRBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceRBtnActionPerformed
        // TODO add your handling code here:
        cashRBtn.setSelected(false);
        insuranceRBtn.setSelected(true);
    }//GEN-LAST:event_insuranceRBtnActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);

        if (showOpenDialogue == JFileChooser.APPROVE_OPTION) {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            patient.setpImageUrl(selectedImagePath);

            ImageIcon ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblPhotoImage.getWidth(), lblPhotoImage.getHeight(), Image.SCALE_SMOOTH);
            lblPhotoImage.setIcon(new ImageIcon(image));
        }
    }//GEN-LAST:event_searchBtnActionPerformed

    private void GenderDropDownListActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GenderDropDownListActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GenderDropDownListActionPerformed

    private void bloodGrpDropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloodGrpDropDownActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bloodGrpDropDownActionPerformed

    private void fNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_fNameTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(fNameTxt.getText());
        if (!match.matches()) {
            lblErrorFname.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorFname.setText(null);
        }
    }//GEN-LAST:event_fNameTxtKeyReleased

    private void lNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lNameTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(lNameTxt.getText());
        if (!match.matches()) {
            lblErrorLname.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorLname.setText(null);
        }
    }//GEN-LAST:event_lNameTxtKeyReleased

    private void injuryTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_injuryTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(injuryTxt.getText());
        if (!match.matches()) {
            lblErrorInjury.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorInjury.setText(null);
        }
    }//GEN-LAST:event_injuryTxtKeyReleased

    private void userNameTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_userNameTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(userNameTxt.getText());
        if (!match.matches()) {
            lblErrorUserName.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorUserName.setText(null);
        }
    }//GEN-LAST:event_userNameTxtKeyReleased

    private void insuranceIdTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_insuranceIdTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(insuranceIdTxt.getText());
        if (!match.matches()) {
            lblErrorHId.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorHId.setText(null);
        }
    }//GEN-LAST:event_insuranceIdTxtKeyReleased

    private void addressTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_addressTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9 '/:]+$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(addressTxt.getText());
        if (!match.matches()) {
            lblErrorAddress.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorAddress.setText(null);
        }
    }//GEN-LAST:event_addressTxtKeyReleased

    private void mobiletTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_mobiletTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9 +()-]{10,18}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(mobiletTxt.getText());
        if (!match.matches()) {
            lblErrorPhone.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorPhone.setText(null);
        }
    }//GEN-LAST:event_mobiletTxtKeyReleased

    private void emailTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_emailTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z0-9]{0,30}[@][a-zA-Z0-9]{0,10}[.][a-zA-Z]{0,5}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(emailTxt.getText());
        if (!match.matches()) {
            lblErrorEmail.setText("Wrong Input. Please Try Again.");
        } else {
            lblErrorEmail.setText(null);
        }
    }//GEN-LAST:event_emailTxtKeyReleased

    private void accidentLocTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accidentLocTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accidentLocTxtActionPerformed

    private void fNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fNameTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        ReceptionWorkAreaJPanel patientBillJPanel = new ReceptionWorkAreaJPanel(userProCont,userAcc,ecoSystem);
        userProCont.add("Patient Bill", patientBillJPanel);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_backBtnActionPerformed

    private void mobiletTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mobiletTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mobiletTxtActionPerformed

    public int CalculateAge(Date birthDate, Date currentDate) {
        // validate inputs ...                                                                               
        DateFormat formatter = new SimpleDateFormat("yyyyMMdd");
        int d1 = Integer.parseInt(formatter.format(birthDate));
        int d2 = Integer.parseInt(formatter.format(currentDate));
        int age = (d2 - d1) / 10000;
        return age;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> GenderDropDownList;
    private javax.swing.JTextField accidentLocTxt;
    private javax.swing.JTextField addressTxt;
    private javax.swing.JButton backBtn;
    private com.toedter.calendar.JDateChooser birthDateBox;
    private javax.swing.JComboBox<String> bloodGrpDropDown;
    private javax.swing.JRadioButton cashRBtn;
    private javax.swing.JTextField emailTxt;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JTextField injuryTxt;
    private javax.swing.JTextField insuranceIdTxt;
    private javax.swing.JRadioButton insuranceRBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lNameTxt;
    private javax.swing.JLabel lblAccidentLocation;
    private javax.swing.JLabel lblAddress4;
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblErrorAccidentLocation;
    private javax.swing.JLabel lblErrorAddress;
    private javax.swing.JLabel lblErrorEmail;
    private javax.swing.JLabel lblErrorFname;
    private javax.swing.JLabel lblErrorHId;
    private javax.swing.JLabel lblErrorInjury;
    private javax.swing.JLabel lblErrorLname;
    private javax.swing.JLabel lblErrorPhone;
    private javax.swing.JLabel lblErrorUserName;
    private javax.swing.JLabel lblPatientAddress;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientGender;
    private javax.swing.JLabel lblPatientHealthInsuranceID;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPatientPhone;
    private javax.swing.JLabel lblPaymentMethod;
    private javax.swing.JLabel lblPhoneNumber4;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoImage;
    private javax.swing.JLabel lblRestaurantName4;
    private javax.swing.JLabel lblUpdatePatient;
    private javax.swing.JTextField mobiletTxt;
    private javax.swing.JButton searchBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
