/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface.Ambulance;

import BusinessModel.Ambulance.Ambulance;
import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.Roles.Patient_role;
import BusinessModel.UserAccount.User;
import BusinessUtil.GoogleMaps.GoogleMapsAmbulanceJPanel;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import MainUserInterface.ReceptionRole.ReceptionWorkArea;

/**
 *
 * @author daddy
 */
public class AmbulanceReceptionWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form AmbulanceReceptionWorkArea
     */
    private final JPanel userProcessContainer;
    private final Ecosystem ecoSystem;
    User userAccount;
    Ambulance ambulance;

    public AmbulanceReceptionWorkArea(JPanel userProcessContainer, Ecosystem ecoSystem, User userAccount, Ambulance ambulance) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.ambulance = ambulance;
    }
    
    public AmbulanceReceptionWorkArea(JPanel userProcessContainer, Ecosystem ecoSystem, User userAccount, Ambulance ambulance, Patient patientDetails) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecoSystem = ecoSystem;
        this.ambulance = ambulance;
        setUpTextFields(patientDetails);
    }
    
    public void setUpTextFields(Patient p){
        txtPatientUserName.setText(p.getpUserName());
        txtPatientFirstName.setText(p.getpFirstName());
        txtPatientLastName.setText(p.getpLastName());
        txtPatientLocation.setText(p.getpAccidentLocation());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblPatientFirstName = new javax.swing.JLabel();
        txtPatientFirstName = new javax.swing.JTextField();
        lblPatientLocation = new javax.swing.JLabel();
        txtPatientLocation = new javax.swing.JTextField();
        subBtn = new javax.swing.JButton();
        lblPatientLastName = new javax.swing.JLabel();
        txtPatientLastName = new javax.swing.JTextField();
        lblPatientUserName = new javax.swing.JLabel();
        lblPatientPassword = new javax.swing.JLabel();
        txtPatientPassword = new javax.swing.JTextField();
        txtPatientUserName = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        viewRouteBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("REGISTER AN EMERGENCY");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 480, 80));

        lblPatientFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientFirstName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientFirstName.setText("Patient First Name");
        add(lblPatientFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 180, -1, -1));

        txtPatientFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientFirstNameActionPerformed(evt);
            }
        });
        add(txtPatientFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 180, 250, 30));

        lblPatientLocation.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientLocation.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientLocation.setText("Patient Location");
        add(lblPatientLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 280, 174, -1));

        txtPatientLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientLocationActionPerformed(evt);
            }
        });
        add(txtPatientLocation, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 280, 250, 30));

        subBtn.setBackground(new java.awt.Color(0, 0, 204));
        subBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        subBtn.setForeground(new java.awt.Color(255, 255, 255));
        subBtn.setText("SUBMIT");
        subBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                subBtnActionPerformed(evt);
            }
        });
        add(subBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 440, 100, 30));

        lblPatientLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientLastName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientLastName.setText("Patient Last Name");
        add(lblPatientLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 230, -1, -1));

        txtPatientLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPatientLastNameActionPerformed(evt);
            }
        });
        add(txtPatientLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 230, 250, 30));

        lblPatientUserName.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientUserName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientUserName.setText("Patient User Name");
        add(lblPatientUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 340, -1, 20));

        lblPatientPassword.setBackground(new java.awt.Color(255, 255, 255));
        lblPatientPassword.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblPatientPassword.setText("Patient Password");
        add(lblPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 390, -1, -1));
        add(txtPatientPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 390, 250, 30));
        add(txtPatientUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(1110, 330, 250, 30));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 1432, 10));

        viewRouteBtn.setBackground(new java.awt.Color(0, 0, 204));
        viewRouteBtn.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        viewRouteBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewRouteBtn.setText("VIEW ROUTE");
        viewRouteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRouteBtnActionPerformed(evt);
            }
        });
        add(viewRouteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 440, 130, 30));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/register emergency.gif"))); // NOI18N
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 120, 520, 390));
    }// </editor-fold>//GEN-END:initComponents

    private void txtPatientLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientLocationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientLocationActionPerformed

    private void subBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_subBtnActionPerformed
        // TODO add your handling code here:
        if (ecoSystem.getUserAccountDirectory().checkIfUsernameIsUnique(txtPatientUserName.getText())) {
            
            Patient patient = new Patient(txtPatientUserName.getText());
            patient.setpFirstName(txtPatientFirstName.getText());
            patient.setpLastName(txtPatientLastName.getText());
            patient.setpAccidentLocation(txtPatientLocation.getText());
            patient.setpStatus("NewPatient");
            patient.setpBloodBankStatus("NewPatient");
            patient.setpPharmaStatus("NewPatient");
            patient.setpLabStatus("NewPatient");
            patient.setpDateOfAdmit(java.util.Calendar.getInstance().getTime());
            ambulance.setStatus("Busy");
            ambulance.setAcciLocation(txtPatientLocation.getText());
            ambulance.getAmbuPatientsList().add(patient);

            ecoSystem.getUserAccountDirectory().createUser(txtPatientUserName.getText(), txtPatientPassword.getText(), null, new Patient_role());
            ecoSystem.getPatientDirect().createPatient(patient);
            for (Patient p : ecoSystem.getPatientDirect().getPatientList()) {
                if (p.getpUserName().equals(txtPatientUserName.getText())) {
                    ecoSystem.getPatientDirect().AddBill(p, "Bed Charge", "Hospital", "Ammount");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Username is not Unique.");
        }
        
        JOptionPane.showMessageDialog(null, "Help Is On The Way");
        
        ReceptionWorkArea receptionWorkAreaJPanel = new ReceptionWorkArea(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("Reception Work Area", receptionWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_subBtnActionPerformed

    private void viewRouteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRouteBtnActionPerformed
        // TODO add your handling code here:
       /*ReceptionWorkArea receptionWorkAreaJPanel = new ReceptionWorkArea(userProcessContainer, userAccount, ecoSystem);
        userProcessContainer.add("Reception Work Area", receptionWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        */
            Patient patient = new Patient(txtPatientUserName.getText());
            patient.setpFirstName(txtPatientFirstName.getText());
            patient.setpLastName(txtPatientLastName.getText());
            patient.setpAccidentLocation(txtPatientLocation.getText());
            patient.setpStatus("NewPatient");
            patient.setpBloodBankStatus("NewPatient");
            patient.setpPharmaStatus("NewPatient");
            patient.setpLabStatus("NewPatient");
            patient.setpDateOfAdmit(java.util.Calendar.getInstance().getTime());
            
       GoogleMapsAmbulanceJPanel GoogleMapsWorkAreaJPanel = new GoogleMapsAmbulanceJPanel(userProcessContainer, ecoSystem, userAccount, ambulance, txtPatientLocation.getText(), patient);
        userProcessContainer.add("Google Maps Work Area", GoogleMapsWorkAreaJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
        
    }//GEN-LAST:event_viewRouteBtnActionPerformed

    private void txtPatientFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientFirstNameActionPerformed

    private void txtPatientLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPatientLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPatientLastNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblPatientFirstName;
    private javax.swing.JLabel lblPatientLastName;
    private javax.swing.JLabel lblPatientLocation;
    private javax.swing.JLabel lblPatientPassword;
    private javax.swing.JLabel lblPatientUserName;
    private javax.swing.JButton subBtn;
    private javax.swing.JTextField txtPatientFirstName;
    private javax.swing.JTextField txtPatientLastName;
    private javax.swing.JTextField txtPatientLocation;
    private javax.swing.JTextField txtPatientPassword;
    private javax.swing.JTextField txtPatientUserName;
    private javax.swing.JButton viewRouteBtn;
    // End of variables declaration//GEN-END:variables
}
