/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Lab;

import BusinessModel.Ecosystem;
import BusinessModel.Labs.Tests;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daddy
 */
public class LabCRUDtests extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkArea
     */
    private JPanel userProcessContainer;
    private Ecosystem ecosystem;
    private User userAccount;
    private Tests t;

    public LabCRUDtests(JPanel userProcessContainer, User account, Ecosystem business) {
        initComponents();
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = business;
        this.userAccount = account;
        populatetableTests();

    }

    private void populatetableTests() {
        DefaultTableModel model = (DefaultTableModel) tableTests.getModel();

        model.setRowCount(0);

        for (Tests t : ecosystem.getLabs().getTestList()) {

            Object[] row = new Object[3];
            row[0] = t;
            row[1] = t.getTestUsage();
            row[2] = t.getTestPrice();
            model.addRow(row);

        }
    }

    private void txtTelephoneNumberKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTests = new javax.swing.JTable();
        lblName = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        lblName2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtUsage = new javax.swing.JTextField();
        txtPrice = new javax.swing.JTextField();
        addTestBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        saveUpdateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laboratory");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 20, 150, 44));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 1390, 10));

        tableTests.setBackground(new java.awt.Color(153, 255, 153));
        tableTests.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        tableTests.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        tableTests.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Test Name", "Test Usage", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tableTests);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 1050, 210));

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblName.setText("Test Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 500, -1, 30));

        lblName1.setBackground(new java.awt.Color(0, 0, 0));
        lblName1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblName1.setText("Usage");
        add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 500, -1, 30));

        lblName2.setBackground(new java.awt.Color(0, 0, 0));
        lblName2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        lblName2.setText("Price");
        add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 500, -1, 30));

        txtName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNameActionPerformed(evt);
            }
        });
        add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 530, 260, 40));
        add(txtUsage, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 530, 260, 40));

        txtPrice.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPriceKeyReleased(evt);
            }
        });
        add(txtPrice, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 530, 260, 40));

        addTestBtn.setBackground(new java.awt.Color(51, 204, 0));
        addTestBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        addTestBtn.setForeground(new java.awt.Color(255, 255, 255));
        addTestBtn.setText("Add Test");
        addTestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addTestBtnActionPerformed(evt);
            }
        });
        add(addTestBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 600, 150, -1));

        deleteBtn.setBackground(new java.awt.Color(255, 0, 51));
        deleteBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 380, 100, 41));

        updateBtn.setBackground(new java.awt.Color(15, 85, 177));
        updateBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 380, 100, 41));

        saveUpdateBtn.setBackground(new java.awt.Color(153, 153, 153));
        saveUpdateBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        saveUpdateBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveUpdateBtn.setText("Save Update");
        saveUpdateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveUpdateBtnActionPerformed(evt);
            }
        });
        add(saveUpdateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 650, 150, -1));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(1150, 490, 120, 32));

        backBtn.setBackground(new java.awt.Color(51, 51, 255));
        backBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/lab.png"))); // NOI18N
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void addTestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addTestBtnActionPerformed

        if (txtName.getText().equals("") || txtUsage.getText().equals("") || txtPrice.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the details");

        } else {
            Tests t = new Tests();
            t.setTestName(txtName.getText());
            t.setTestUsage(txtUsage.getText());
            t.setTestPrice(Integer.parseInt(txtPrice.getText()));
            ecosystem.getLabs().createTest(t);

            populatetableTests();

        }

        txtName.setText("");
        txtUsage.setText("");
        txtPrice.setText("");
    }//GEN-LAST:event_addTestBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableTests.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Delete Test: " + tableTests.getValueAt(selectedRow, 0) + " ??", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {

                Tests p = (Tests) tableTests.getValueAt(selectedRow, 0);

                ecosystem.getLabs().deleteTests(p);
                populatetableTests();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Select a Row!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = tableTests.getSelectedRow();
        //Tests p = (Tests) tableTests.getValueAt(selectedRow, 0);
        if (selectedRow >= 0) {
            t = (Tests) tableTests.getValueAt(selectedRow, 0);
            txtName.setText(t.getTestName());
            txtUsage.setText(t.getTestUsage());
            txtPrice.setText(Integer.toString(t.getTestPrice()));
            // system.getUserAccountDirectory().deleteUserAccount(user);

        } else {
            JOptionPane.showMessageDialog(null, "Please select a row");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void saveUpdateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveUpdateBtnActionPerformed
        // TODO add your handling code here:

        String name = txtName.getText();
        String uname = txtUsage.getText();
        String password = txtPrice.getText();
        if (name.equalsIgnoreCase("") || uname.equalsIgnoreCase("") || password.equalsIgnoreCase("")) {
            JOptionPane.showMessageDialog(null, "Pls, Fill data Correctly!!", "Warning", JOptionPane.WARNING_MESSAGE);
        } else {

            ecosystem.getLabs().updateTests(t, name, uname, Integer.parseInt(password));
            populatetableTests();
        }
        txtName.setText("");
        txtUsage.setText("");
        txtPrice.setText("");
    }//GEN-LAST:event_saveUpdateBtnActionPerformed

    private void txtPriceKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPriceKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtPrice.getText());
        if (!match.matches() )
        {
            jLabel2.setText("Wrong Input. Please Try Again.");
        } else {
            jLabel2.setText(null);
        }
    }//GEN-LAST:event_txtPriceKeyReleased

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //patient.setInsuranceStatus("Approved");
        LabWorkArea bill = new LabWorkArea(userProcessContainer, userAccount, ecosystem);
        userProcessContainer.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_backBtnActionPerformed

    private void txtNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addTestBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JButton saveUpdateBtn;
    private javax.swing.JTable tableTests;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPrice;
    private javax.swing.JTextField txtUsage;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
