/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Lab;

import BusinessModel.Ecosystem;
import BusinessModel.Labs.Tests;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daddy
 */
public class LabWorkArea extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkArea
     */
    private JPanel userProcessContainer;
    private Ecosystem ecosystem;
    private User userAccount;
    private Tests t;
    
    public LabWorkArea(JPanel userProcessContainer, User account, Ecosystem business) {
        
        initComponents();
        System.out.println("with in LabWorkAreaJPanel");
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = business;
        this.userAccount = account;
        populatePatientTable1();
        populatePatientTable();
    }

    
        private void populatePatientTable1() {
        DefaultTableModel model = (DefaultTableModel) managePatientTable1.getModel();
        model.setRowCount(0);
        for (Patient patient : this.ecosystem.getLabs().getLabRecordsList()) {
            Object[] row = new Object[7];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = patient.getpHealthInsuranceID();
            row[3] = patient.getpAge();
            row[4] = patient.getpEmailAddress();
            row[5] = patient.getpLabStatus();
            row[6] = patient;
            if(!patient.getpLabStatus().equals("Delivered")){
            model.addRow(row);}

        }
    }
    private void populatePatientTable() {
            DefaultTableModel model = (DefaultTableModel) managePatientTable2.getModel();
            model.setRowCount(0);
            for (Patient patient : this.ecosystem.getLabs().getLabRecordsList()) {
                Object[] row = new Object[7];
                row[0] = patient.getpFirstName();
                row[1] = patient.getpLastName();
                row[2] = patient.getpHealthInsuranceID();
                row[3] = patient.getpAge();
                row[4] = patient.getpEmailAddress();
                row[5] = patient.getpLabStatus();
                row[6] = patient;
                if(patient.getpLabStatus().equals("Delivered")){
                model.addRow(row);}
            }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        availTestInformationBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        managePatientTable1 = new javax.swing.JTable();
        viewReqBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        viewRequBtn = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        managePatientTable2 = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Laboratory Center");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 40, 230, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 79, 1295, 10));

        availTestInformationBtn.setBackground(new java.awt.Color(0, 0, 255));
        availTestInformationBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        availTestInformationBtn.setForeground(new java.awt.Color(255, 255, 255));
        availTestInformationBtn.setText("Available Tests Info");
        availTestInformationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                availTestInformationBtnActionPerformed(evt);
            }
        });
        add(availTestInformationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 190, 210, -1));

        managePatientTable1.setBackground(new java.awt.Color(153, 255, 153));
        managePatientTable1.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        managePatientTable1.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        managePatientTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "HealthId", "Age", "Email", "LabStatus", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(managePatientTable1);
        if (managePatientTable1.getColumnModel().getColumnCount() > 0) {
            managePatientTable1.getColumnModel().getColumn(6).setMinWidth(0);
            managePatientTable1.getColumnModel().getColumn(6).setPreferredWidth(0);
            managePatientTable1.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 1053, 188));

        viewReqBtn.setBackground(new java.awt.Color(0, 0, 255));
        viewReqBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        viewReqBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewReqBtn.setText("View Request");
        viewReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReqBtnActionPerformed(evt);
            }
        });
        add(viewReqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 510, 150, 30));

        jLabel2.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel2.setText("Past Requests");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 510, 163, 30));

        jLabel3.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        jLabel3.setText("Current Requests");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 185, 25));

        viewRequBtn.setBackground(new java.awt.Color(0, 0, 255));
        viewRequBtn.setFont(new java.awt.Font("Microsoft JhengHei", 1, 18)); // NOI18N
        viewRequBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewRequBtn.setText("View Request");
        viewRequBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewRequBtnActionPerformed(evt);
            }
        });
        add(viewRequBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 700, 158, 30));

        managePatientTable2.setBackground(new java.awt.Color(153, 255, 153));
        managePatientTable2.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        managePatientTable2.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        managePatientTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "First Name", "Last Name", "HealthId", "Age", "Email", "LabStatus", "Obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(managePatientTable2);
        if (managePatientTable2.getColumnModel().getColumnCount() > 0) {
            managePatientTable2.getColumnModel().getColumn(6).setMinWidth(0);
            managePatientTable2.getColumnModel().getColumn(6).setPreferredWidth(0);
            managePatientTable2.getColumnModel().getColumn(6).setMaxWidth(0);
        }

        add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 550, 1053, 137));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/icons8-lab-50.png"))); // NOI18N
        jLabel4.setText("jLabel4");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 50, 50));
    }// </editor-fold>//GEN-END:initComponents

    private void availTestInformationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_availTestInformationBtnActionPerformed
        // TODO add your handling code here:
        LabCRUDtests doctorRequestLabTestJPanel = new LabCRUDtests(userProcessContainer, userAccount,ecosystem);
        userProcessContainer.add("Request Lab Tests", doctorRequestLabTestJPanel);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_availTestInformationBtnActionPerformed

    private void viewReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReqBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = managePatientTable1.getSelectedRow();
        if (selectedRowIndex < 0) 
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else 
        {
            Patient patient = (Patient) managePatientTable1.getValueAt(selectedRowIndex, 6);
            LabRequestedTests doctorRequestLabTestJPanel = new LabRequestedTests(userProcessContainer, userAccount,patient,ecosystem);
            userProcessContainer.add("Request Lab Tests", doctorRequestLabTestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
        
        
    }//GEN-LAST:event_viewReqBtnActionPerformed

    private void viewRequBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewRequBtnActionPerformed
        // TODO add your handling code here:
                int selectedRowIndex = managePatientTable2.getSelectedRow();
        if (selectedRowIndex < 0) 
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else 
        {
            Patient patient = (Patient) managePatientTable2.getValueAt(selectedRowIndex, 6);
            LabPastRequestedTests doctorRequestLabTestJPanel = new LabPastRequestedTests(userProcessContainer, userAccount,patient,ecosystem);
            userProcessContainer.add("Past Lab Tests", doctorRequestLabTestJPanel);
            CardLayout layout = (CardLayout) userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        }
    }//GEN-LAST:event_viewRequBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton availTestInformationBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable managePatientTable1;
    private javax.swing.JTable managePatientTable2;
    private javax.swing.JButton viewReqBtn;
    private javax.swing.JButton viewRequBtn;
    // End of variables declaration//GEN-END:variables
}
