/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Pharmacy;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.Pharma.Medicine;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indian
 */
public class PharmacyWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkAreaJPanel
     */
    JPanel userProCont;
    Ecosystem ecosystem;
    User userAcc;
    Medicine med;
    
    public PharmacyWorkAreaJPanel(JPanel userProcessContainer, User account, Ecosystem business) {
        initComponents();
        this.userProCont = userProcessContainer;
        this.ecosystem = business;
        this.userAcc = account;
        //populatetableMedicine();
        populatePatientTable();
        populatePatientTable1();
    }
    private void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) managePatientTable.getModel();

        model.setRowCount(0);

        for (Patient patient : ecosystem.getPharma().getPharmaRecordList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = patient.getpPharmaStatus();
            row[3] = patient.getpHealthInsuranceID();
            row[4] = patient.getpAge();
            row[5] = patient.getpAddress();
            row[6] = patient.getpEmailAddress();
            row[7] = patient;
           if(patient.getpPharmaStatus().equals("Requested")){
            model.addRow(row);
           }
        }
    }
        private void populatePatientTable1() {
        DefaultTableModel model = (DefaultTableModel) managePatientTable1.getModel();

        model.setRowCount(0);

        for (Patient patient : ecosystem.getPharma().getPharmaRecordList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = patient.getpPharmaStatus();
            row[3] = patient.getpHealthInsuranceID();
            row[4] = patient.getpAge();
            row[5] = patient.getpAddress();
            row[6] = patient.getpEmailAddress();
            row[7] = patient;
           if(patient.getpPharmaStatus().equals("Delivered")){
            model.addRow(row);
           }
        }
    }
          /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        viewReqBtn = new javax.swing.JButton();
        updateInventoryBtn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        managePatientTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        managePatientTable1 = new javax.swing.JTable();
        viewReqBtn2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharmacy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 40, 200, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1221, 10));

        viewReqBtn.setBackground(new java.awt.Color(51, 51, 51));
        viewReqBtn.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        viewReqBtn.setForeground(new java.awt.Color(255, 255, 204));
        viewReqBtn.setText("View Request");
        viewReqBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewReqBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReqBtnActionPerformed(evt);
            }
        });
        add(viewReqBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(893, 354, 160, 41));

        updateInventoryBtn.setBackground(new java.awt.Color(51, 51, 51));
        updateInventoryBtn.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        updateInventoryBtn.setForeground(new java.awt.Color(255, 255, 204));
        updateInventoryBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/update.png"))); // NOI18N
        updateInventoryBtn.setText("Update Inventory");
        updateInventoryBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        updateInventoryBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateInventoryBtnActionPerformed(evt);
            }
        });
        add(updateInventoryBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 354, 220, 41));

        managePatientTable.setBackground(new java.awt.Color(255, 255, 153));
        managePatientTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePatientTable.setFont(new java.awt.Font("Futura", 0, 12)); // NOI18N
        managePatientTable.setForeground(new java.awt.Color(102, 102, 0));
        managePatientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First", "Last", "PharmaStatus", "HealthId", "Age", "Address", "Email", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(managePatientTable);
        if (managePatientTable.getColumnModel().getColumnCount() > 0) {
            managePatientTable.getColumnModel().getColumn(7).setMinWidth(0);
            managePatientTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            managePatientTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 132, 931, 195));

        managePatientTable1.setBackground(new java.awt.Color(255, 255, 153));
        managePatientTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        managePatientTable1.setFont(new java.awt.Font("Futura", 0, 12)); // NOI18N
        managePatientTable1.setForeground(new java.awt.Color(102, 102, 0));
        managePatientTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "First", "Last", "PharmaStatus", "HealthId", "Age", "Address", "Email", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true, true, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(managePatientTable1);
        if (managePatientTable1.getColumnModel().getColumnCount() > 0) {
            managePatientTable1.getColumnModel().getColumn(7).setMinWidth(0);
            managePatientTable1.getColumnModel().getColumn(7).setPreferredWidth(0);
            managePatientTable1.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(123, 441, 942, 191));

        viewReqBtn2.setBackground(new java.awt.Color(51, 51, 51));
        viewReqBtn2.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        viewReqBtn2.setForeground(new java.awt.Color(255, 255, 204));
        viewReqBtn2.setText("View Request");
        viewReqBtn2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        viewReqBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewReqBtn2ActionPerformed(evt);
            }
        });
        add(viewReqBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(904, 650, 160, 41));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/drugstore.png"))); // NOI18N
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 10, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void viewReqBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReqBtnActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = managePatientTable.getSelectedRow();
        if (selectedRowIndex < 0) 
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else 
        {
            Patient patient = (Patient) managePatientTable.getValueAt(selectedRowIndex, 7);
            PharmacyRequestedTests doctorRequestLabTestJPanel = new PharmacyRequestedTests(userProCont, userAcc,patient,ecosystem);
            userProCont.add("Request Lab Tests", doctorRequestLabTestJPanel);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);
        }

    }//GEN-LAST:event_viewReqBtnActionPerformed

    private void updateInventoryBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateInventoryBtnActionPerformed
        // TODO add your handling code here:
        PharmacyCRUDJpanel doctorRequestLabTestJPanel = new PharmacyCRUDJpanel(userProCont, userAcc,ecosystem);
        userProCont.add("Request Lab Tests", doctorRequestLabTestJPanel);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_updateInventoryBtnActionPerformed

    private void viewReqBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewReqBtn2ActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = managePatientTable1.getSelectedRow();
        if (selectedRowIndex < 0) 
        {
            JOptionPane.showMessageDialog(null, "Please select a row from the table to view details", "Warning", JOptionPane.WARNING_MESSAGE);
        } 
        else 
        {
            Patient patient = (Patient) managePatientTable1.getValueAt(selectedRowIndex, 7);
            PharmacyPastRequest doctorRequestLabTestJPanel = new PharmacyPastRequest(userProCont, userAcc,patient,ecosystem);
            userProCont.add("Past Tests", doctorRequestLabTestJPanel);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);
        }
    }//GEN-LAST:event_viewReqBtn2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable managePatientTable;
    private javax.swing.JTable managePatientTable1;
    private javax.swing.JButton updateInventoryBtn;
    private javax.swing.JButton viewReqBtn;
    private javax.swing.JButton viewReqBtn2;
    // End of variables declaration//GEN-END:variables
}
