/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Pharmacy;

import BusinessModel.Ecosystem;
import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.Pharma.Medicine;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indian
 */
public class PharmacyCRUDJpanel extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkAreaJPanel
     */
    JPanel userProCont;
    Ecosystem ecoSystem;
    User userAcc;
    Medicine m;
    
    public PharmacyCRUDJpanel(JPanel userProcessContainer, User account, Ecosystem business) {
        initComponents();
        this.userProCont = userProcessContainer;
        this.ecoSystem = business;
        this.userAcc = account;
        populateMedicineTable();
        //populatePatientTable();
    }
    
        private void populateMedicineTable() {
        DefaultTableModel model = (DefaultTableModel) testsTable.getModel();

        model.setRowCount(0);

        for (Medicine t : ecoSystem.getPharma().getmedList()) {

            
                Object[] row = new Object[4];                
                row[0] = t;
                row[1] = t.getMedUsage();
                row[2] =t.getMedQuant();
                row[3] = t.getMedPrice();
                model.addRow(row);
            

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        addMedBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        testsTable = new javax.swing.JTable();
        lblName2 = new javax.swing.JLabel();
        medPriceTxt = new javax.swing.JTextField();
        medUsageTxt = new javax.swing.JTextField();
        medNameTxt = new javax.swing.JTextField();
        lblName = new javax.swing.JLabel();
        lblName1 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        lblName3 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Pharmacy");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 70, 230, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 139, 1328, 10));

        addMedBtn.setBackground(new java.awt.Color(51, 51, 51));
        addMedBtn.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        addMedBtn.setForeground(new java.awt.Color(255, 255, 204));
        addMedBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/add.png"))); // NOI18N
        addMedBtn.setText("Add Medicine");
        addMedBtn.setBorder(null);
        addMedBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMedBtnActionPerformed(evt);
            }
        });
        add(addMedBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 600, 210, 40));

        testsTable.setBackground(new java.awt.Color(255, 255, 153));
        testsTable.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)));
        testsTable.setFont(new java.awt.Font("Futura", 0, 12)); // NOI18N
        testsTable.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        testsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Med Name", "Med Usage", "Quantity", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(testsTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(229, 177, 788, 186));

        lblName2.setBackground(new java.awt.Color(0, 0, 0));
        lblName2.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        lblName2.setForeground(new java.awt.Color(102, 102, 0));
        lblName2.setText("Price");
        add(lblName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 540, -1, 30));

        medPriceTxt.setBackground(new java.awt.Color(255, 255, 153));
        medPriceTxt.setForeground(new java.awt.Color(153, 153, 0));
        medPriceTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(153, 153, 0))); // NOI18N
        medPriceTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                medPriceTxtKeyReleased(evt);
            }
        });
        add(medPriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 550, 144, 30));

        medUsageTxt.setBackground(new java.awt.Color(255, 255, 153));
        medUsageTxt.setForeground(new java.awt.Color(153, 153, 0));
        medUsageTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(153, 153, 0))); // NOI18N
        add(medUsageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 440, 144, 30));

        medNameTxt.setBackground(new java.awt.Color(255, 255, 153));
        medNameTxt.setForeground(new java.awt.Color(153, 153, 0));
        medNameTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(153, 153, 0))); // NOI18N
        add(medNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 144, 30));

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 0));
        lblName.setText("Medicine Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 380, -1, 30));

        lblName1.setBackground(new java.awt.Color(0, 0, 0));
        lblName1.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        lblName1.setForeground(new java.awt.Color(102, 102, 0));
        lblName1.setText("Medicine Usage");
        add(lblName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 430, -1, 30));

        quantityTxt.setBackground(new java.awt.Color(255, 255, 153));
        quantityTxt.setForeground(new java.awt.Color(153, 153, 0));
        quantityTxt.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED), "", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Helvetica Neue", 0, 13), new java.awt.Color(153, 153, 0))); // NOI18N
        quantityTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                quantityTxtKeyReleased(evt);
            }
        });
        add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 490, 144, 30));

        lblName3.setBackground(new java.awt.Color(0, 0, 0));
        lblName3.setFont(new java.awt.Font("Futura", 1, 18)); // NOI18N
        lblName3.setForeground(new java.awt.Color(102, 102, 0));
        lblName3.setText("Quantity");
        add(lblName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 490, -1, 30));

        deleteBtn.setBackground(new java.awt.Color(51, 51, 51));
        deleteBtn.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 204));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/delete.png"))); // NOI18N
        deleteBtn.setText("Delete");
        deleteBtn.setBorder(null);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        add(deleteBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 660, 210, 43));

        saveBtn.setBackground(new java.awt.Color(51, 51, 51));
        saveBtn.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 204));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/save.png"))); // NOI18N
        saveBtn.setText("Save Update");
        saveBtn.setBorder(null);
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        add(saveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 660, 190, 43));

        updateBtn.setBackground(new java.awt.Color(51, 51, 51));
        updateBtn.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 204));
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/update.png"))); // NOI18N
        updateBtn.setText("Update");
        updateBtn.setBorder(null);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 600, 188, 40));
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 490, 213, 32));
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, 213, 32));

        backBtn.setFont(new java.awt.Font("Futura", 0, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 0, 0));
        backBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/back.png"))); // NOI18N
        backBtn.setText("Back");
        backBtn.setBorder(null);
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 80, 130, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/drugstore.png"))); // NOI18N
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addMedBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMedBtnActionPerformed

        if (medNameTxt.getText().equals("") || medUsageTxt.getText().equals("")|| medPriceTxt.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Please fill all the details");
        } else {
            Medicine m = new Medicine();
            m.setMedName(medNameTxt.getText());
            m.setMedQuant(Integer.parseInt(quantityTxt.getText()));
            m.setMedUsage(medUsageTxt.getText());
            m.setMedPrice(Integer.parseInt(medPriceTxt.getText()));
            ecoSystem.getPharma().createMedicine(m);

            populateMedicineTable();

        }

        medNameTxt.setText("");
        medUsageTxt.setText("");
        medPriceTxt.setText("");
        quantityTxt.setText("");
    }//GEN-LAST:event_addMedBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = testsTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Delete Medicine: "+testsTable.getValueAt(selectedRow, 0)+" ??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){

                Medicine p = (Medicine) testsTable.getValueAt(selectedRow, 0);
                ecoSystem.getPharma().deleteMed(p);
                populateMedicineTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Select a Customer to delete!");
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:

        String name = medNameTxt.getText();
        String uname=medUsageTxt.getText();
        String password=medPriceTxt.getText();
        String quantity= quantityTxt.getText();
        if(name.equalsIgnoreCase("")||uname.equalsIgnoreCase("")||password.equalsIgnoreCase(""))
        {
            JOptionPane.showMessageDialog(null, "Pls, Fill data Correctly!!", "Warning", JOptionPane.WARNING_MESSAGE);
        }
        else{

            ecoSystem.getPharma().updateMeds(m,name,uname,Integer.parseInt(password),Integer.parseInt(quantity));
            populateMedicineTable();
        }
        medNameTxt.setText("");
        medUsageTxt.setText("");
        medPriceTxt.setText("");
        quantityTxt.setText("");
    }//GEN-LAST:event_saveBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = testsTable.getSelectedRow();
        //Tests p = (Tests) tableTests.getValueAt(selectedRow, 0);
        if(selectedRow>=0){
            m = (Medicine) testsTable.getValueAt(selectedRow, 0);
            medNameTxt.setText(m.getMedName());
            medUsageTxt.setText(m.getMedUsage());
            medPriceTxt.setText(Integer.toString(m.getMedPrice()));
            quantityTxt.setText(Integer.toString(m.getMedQuant()));
            // system.getUserAccountDirectory().deleteUserAccount(user);

        }
        else {
            JOptionPane.showMessageDialog(null,"Please select a row");
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void quantityTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_quantityTxtKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9]{0,10}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(quantityTxt.getText());
        if (!match.matches() )
        {
            jLabel2.setText("Please input correct data. HINT: number");
        } else 
        {
            jLabel2.setText(null);
        }
    }//GEN-LAST:event_quantityTxtKeyReleased

    private void medPriceTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_medPriceTxtKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[0-9]{0,10}$";
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(medPriceTxt.getText());
        if (!match.matches() )
        {
            jLabel3.setText("Please input correct data. HINT: number");
        } 
        else 
        {
            jLabel3.setText(null);
        }
    }//GEN-LAST:event_medPriceTxtKeyReleased

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //patient.setInsuranceStatus("Approved");
        PharmacyWorkAreaJPanel bill = new PharmacyWorkAreaJPanel(userProCont, userAcc, ecoSystem);
        userProCont.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMedBtn;
    private javax.swing.JButton backBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblName1;
    private javax.swing.JLabel lblName2;
    private javax.swing.JLabel lblName3;
    private javax.swing.JTextField medNameTxt;
    private javax.swing.JTextField medPriceTxt;
    private javax.swing.JTextField medUsageTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable testsTable;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
