/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package MainUserInterface.SystemAdmin;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.Roles.RolePatient;
import BusinessModel.UserAccount.User;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daddy
 */

 
public class ManagePatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManagePatient
     */
    
    private final JPanel userProCont;
    private final Ecosystem ecoSystem;
    User userAcc;
    
    public ManagePatientJPanel(JPanel userProcessContainer, Ecosystem system) {
        initComponents();
        this.userProCont = userProcessContainer;
        this.ecoSystem = system;
        populateTable();
        
    }
    
     private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) ManageCustomersTable.getModel();

        model.setRowCount(0);

        for (User user : ecoSystem.getUserAccountDirectory().getUserAccountList()) {

            if ("Business.Role.PatientRole".equals(user.getRole().getClass().getName())) {
                Object[] row = new Object[3];
                row[1] = user.getUserName();
                row[2] = user.getUserPassword();
                model.addRow(row);
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        ManageCustomersTable = new javax.swing.JTable();
        lblManageCustomers = new javax.swing.JLabel();
        submitBtn = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        passwordTxt = new javax.swing.JPasswordField();
        userNameTxt = new javax.swing.JTextField();
        lblUserName = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        nameTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 204, 204));
        setToolTipText("");
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageCustomersTable.setBackground(new java.awt.Color(153, 153, 153));
        ManageCustomersTable.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ManageCustomersTable.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        ManageCustomersTable.setForeground(new java.awt.Color(51, 51, 51));
        ManageCustomersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Name", "User Name", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        ManageCustomersTable.setSelectionBackground(new java.awt.Color(255, 255, 255));
        ManageCustomersTable.setSelectionForeground(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(ManageCustomersTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(385, 102, 490, 191));

        lblManageCustomers.setBackground(new java.awt.Color(119, 197, 147));
        lblManageCustomers.setFont(new java.awt.Font("Futura", 1, 36)); // NOI18N
        lblManageCustomers.setForeground(new java.awt.Color(51, 51, 51));
        lblManageCustomers.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblManageCustomers.setText("                      Manage Customers");
        add(lblManageCustomers, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 730, 70));

        submitBtn.setBackground(new java.awt.Color(51, 51, 51));
        submitBtn.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        submitBtn.setForeground(new java.awt.Color(204, 204, 204));
        submitBtn.setText("Submit");
        submitBtn.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        submitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitBtnActionPerformed(evt);
            }
        });
        add(submitBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 315, 172, 53));

        lblPassword.setBackground(new java.awt.Color(0, 0, 0));
        lblPassword.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(102, 102, 102));
        lblPassword.setText("Password");
        add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(24, 238, -1, 30));

        passwordTxt.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        passwordTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordTxtActionPerformed(evt);
            }
        });
        add(passwordTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 239, 172, 40));

        userNameTxt.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        userNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTxtActionPerformed(evt);
            }
        });
        add(userNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 170, 172, 37));

        lblUserName.setBackground(new java.awt.Color(0, 0, 0));
        lblUserName.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        lblUserName.setForeground(new java.awt.Color(102, 102, 102));
        lblUserName.setText("Username");
        add(lblUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 168, -1, 30));

        lblName.setBackground(new java.awt.Color(0, 0, 0));
        lblName.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        lblName.setForeground(new java.awt.Color(102, 102, 102));
        lblName.setText("Name");
        add(lblName, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 102, -1, 30));

        nameTxt.setFont(new java.awt.Font("Futura", 1, 24)); // NOI18N
        add(nameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(164, 104, 172, 38));
    }// </editor-fold>//GEN-END:initComponents

    private void submitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitBtnActionPerformed

        Patient patient = new Patient();
        String name = nameTxt.getText();
        String uname = userNameTxt.getText();
        String password = passwordTxt.getText();
        if(name.equals("") || uname.equals("") || password.equals(""))
        {
            JOptionPane.showMessageDialog(null, "Please fill all the details");
        }
        else
        {
             
            ecoSystem.getUserAccountDirectory().createUser(uname, password, null, new RolePatient());
            ecoSystem.getPatientDirect().createPatient(patient);
            populateTable();
        }

        nameTxt.setText("");
        userNameTxt.setText("");
        passwordTxt.setText("");
    }//GEN-LAST:event_submitBtnActionPerformed

    private void passwordTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordTxtActionPerformed

    private void userNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ManageCustomersTable;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblManageCustomers;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUserName;
    private javax.swing.JTextField nameTxt;
    private javax.swing.JPasswordField passwordTxt;
    private javax.swing.JButton submitBtn;
    private javax.swing.JTextField userNameTxt;
    // End of variables declaration//GEN-END:variables
}
