/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.Police;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author daddy
 */
public class PoliceWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkAreaJPanel
     */
    JPanel userProCont;
    User userAcc;
    Ecosystem ecoSystem;
    public PoliceWorkAreaJPanel(JPanel userProcessContainer, User account, Ecosystem business) {
        initComponents();
        this.userProCont = userProcessContainer;
        this.ecoSystem = business;
        this.userAcc = account;
        populatePatientTable();
        populatePatientTable1();
    }
              private void populatePatientTable() {
        DefaultTableModel model = (DefaultTableModel) verificationReqTable.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoSystem.getPoliceRecords().getPoliceRecordsList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();           
            row[2] = patient.getpHealthInsuranceID();
            row[3] = patient.getpAge();
            row[4] = patient.getpAddress();
            row[5] = patient.getpEmailAddress();
            row[6] = patient.getpPoliceStatus();
            row[7] = patient;
            if(patient.getpPoliceStatus().equals("Verifying")){
            model.addRow(row);}

        }
    }
               private void populatePatientTable1() {
        DefaultTableModel model = (DefaultTableModel) pastRecordsTable.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoSystem.getPoliceRecords().getPoliceRecordsList()) {

            Object[] row = new Object[8];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = patient.getpHealthInsuranceID();
            row[3] = patient.getpAge();
            row[4] = patient.getpAddress();
            row[5] = patient.getpEmailAddress();
            row[6] = patient.getpPoliceStatus();
            row[7] = patient;
            if(!patient.getpPoliceStatus().equals("Verifying")){
            model.addRow(row);}

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane3 = new javax.swing.JScrollPane();
        verificationReqTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        pastRecordsTable = new javax.swing.JTable();
        detailsForVerificationBtn = new javax.swing.JButton();
        detailsOfPastRecordsBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 0, 102));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MainUserInterface/Images/police_100x100.png"))); // NOI18N
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 90, 130, 120));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("POLICE DEPATMENT");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, 1260, 80));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 84, 1260, 30));

        verificationReqTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        verificationReqTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "HealthId", "Age", "Address", "Email", "Police Verification", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(verificationReqTable);
        if (verificationReqTable.getColumnModel().getColumnCount() > 0) {
            verificationReqTable.getColumnModel().getColumn(7).setMinWidth(0);
            verificationReqTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            verificationReqTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 250, 1260, 140));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("VERIFICATION REQUEST");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 334, 21));

        jLabel3.setFont(new java.awt.Font("Georgia", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("PAST RECORDS");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, 313, 21));

        pastRecordsTable.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        pastRecordsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "HealthId", "Age", "Address", "Email", "Police Verification", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(pastRecordsTable);
        if (pastRecordsTable.getColumnModel().getColumnCount() > 0) {
            pastRecordsTable.getColumnModel().getColumn(7).setMinWidth(0);
            pastRecordsTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            pastRecordsTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 510, 1260, 191));

        detailsForVerificationBtn.setBackground(new java.awt.Color(0, 51, 255));
        detailsForVerificationBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        detailsForVerificationBtn.setForeground(new java.awt.Color(255, 255, 255));
        detailsForVerificationBtn.setText("View Details of Verification");
        detailsForVerificationBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsForVerificationBtnActionPerformed(evt);
            }
        });
        add(detailsForVerificationBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 410, 316, 30));

        detailsOfPastRecordsBtn.setBackground(new java.awt.Color(0, 0, 255));
        detailsOfPastRecordsBtn.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        detailsOfPastRecordsBtn.setForeground(new java.awt.Color(255, 255, 255));
        detailsOfPastRecordsBtn.setText("View Details of Past Records");
        detailsOfPastRecordsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                detailsOfPastRecordsBtnActionPerformed(evt);
            }
        });
        add(detailsOfPastRecordsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 720, 310, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void detailsForVerificationBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsForVerificationBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = verificationReqTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            Patient d = (Patient) verificationReqTable.getValueAt(selectedRow, 7);
            PersonInfo bill = new PersonInfo(userProCont,ecoSystem, d,userAcc);
            userProCont.add("Police Person Info", bill);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);
                   
          
        }
    }//GEN-LAST:event_detailsForVerificationBtnActionPerformed

    private void detailsOfPastRecordsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_detailsOfPastRecordsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = pastRecordsTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table!","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{
            
            Patient d = (Patient) pastRecordsTable.getValueAt(selectedRow, 7);
            //d.get
            PastInfo bill = new PastInfo(userProCont,ecoSystem, d,userAcc);
            userProCont.add("Past Info", bill);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);
                   
          
        }
    }//GEN-LAST:event_detailsOfPastRecordsBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton detailsForVerificationBtn;
    private javax.swing.JButton detailsOfPastRecordsBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable pastRecordsTable;
    private javax.swing.JTable verificationReqTable;
    // End of variables declaration//GEN-END:variables
}
