/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.InsuranceAuthority;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.PatientBills;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import MainUserInterface.Patient.PatientBillJPanel;

/**
 *
 * @author indian
 */
public class InsurancePastCustomers extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkAreaJPanel
     */
    private final JPanel userProCont;
    private final Ecosystem ecoSystem;
    User userAcc;
    public InsurancePastCustomers(JPanel userProcessContainer, User account, Ecosystem system) {
        initComponents();
        this.userProCont = userProcessContainer;
        this.ecoSystem = system;
        this.userAcc = account;
        
        populatepatientInsurerTable();
        
    }
          
private void populatepatientInsurerTable() {
        DefaultTableModel model = (DefaultTableModel) patientInsurerTable.getModel();

        model.setRowCount(0);

        for (Patient patient : ecoSystem.getInsuranceDirect().getInsuranceRecord()) {

            Object[] row = new Object[7];
            row[0] = patient.getpFirstName();
            row[1] = patient.getpLastName();
            row[2] = Float.toString(ecoSystem.getPatientDirect().billTotal(patient));
            row[3] = patient.getpHealthInsuranceID();
            row[6] = patient.getpInsuranceStatus();
            row[5] = patient.getpPoliceStatus();
            row[4] = patient.getpEmailAddress();
            row[5] = patient;
            if(!patient.getpInsuranceStatus().equals("Verifying Insurance")){
            model.addRow(row);
            }

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane4 = new javax.swing.JScrollPane();
        patientInsurerTable = new javax.swing.JTable();
        viewDetailsBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(153, 153, 0));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Insurer");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-180, 40, 1400, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 126, 1400, 10));

        patientInsurerTable.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        patientInsurerTable.setBackground(new java.awt.Color(255, 255, 204));
        patientInsurerTable.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        patientInsurerTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Name", "Last", "Bill Total", "HealthId", "Email", "Police Verification", "Insurance Status", "obj"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, true, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(patientInsurerTable);
        if (patientInsurerTable.getColumnModel().getColumnCount() > 0) {
            patientInsurerTable.getColumnModel().getColumn(7).setMinWidth(0);
            patientInsurerTable.getColumnModel().getColumn(7).setPreferredWidth(0);
            patientInsurerTable.getColumnModel().getColumn(7).setMaxWidth(0);
        }

        add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 180, 990, 200));

        viewDetailsBtn.setBackground(new java.awt.Color(0, 153, 204));
        viewDetailsBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        viewDetailsBtn.setForeground(new java.awt.Color(255, 255, 255));
        viewDetailsBtn.setText("View Details");
        viewDetailsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewDetailsBtnActionPerformed(evt);
            }
        });
        add(viewDetailsBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 400, 150, 30));

        backBtn.setBackground(new java.awt.Color(0, 153, 204));
        backBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 400, 110, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void viewDetailsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewDetailsBtnActionPerformed
        // TODO add your handling code here:
        int selectedRow = patientInsurerTable.getSelectedRow();
        if(selectedRow<0){
            JOptionPane.showMessageDialog(null,"Please select a row from the table to view details","Warning",JOptionPane.WARNING_MESSAGE);
        }
        else{

            Patient d = (Patient) patientInsurerTable.getValueAt(selectedRow, 5);
            //d.get
            PastCustomerInfo bill = new PastCustomerInfo(userProCont,ecoSystem, d, userAcc);
            userProCont.add("Past Customer", bill);
            CardLayout layout = (CardLayout) userProCont.getLayout();
            layout.next(userProCont);

        }
    }//GEN-LAST:event_viewDetailsBtnActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //patient.setInsuranceStatus("Approved");
        InsuranceWorkAreaJPanel bill = new InsuranceWorkAreaJPanel(userProCont, userAcc, ecoSystem);
        userProCont.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_backBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable patientInsurerTable;
    private javax.swing.JButton viewDetailsBtn;
    // End of variables declaration//GEN-END:variables
}
