/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package MainUserInterface.InsuranceAuthority;

import BusinessModel.Ecosystem;
import BusinessModel.Patient.PatientBills;
import BusinessModel.Patient.Patient;
import BusinessModel.UserAccount.User;
import java.awt.CardLayout;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author indian
 */
public class PastCustomerInfo extends javax.swing.JPanel {

    /**
     * Creates new form LabWorkAreaJPanel
     */
        JPanel userProCont;
    Patient pat;
    User userAcc;
    Ecosystem ecoSystem;
    public PastCustomerInfo(JPanel userProcessContainer, Ecosystem business, Patient p, User account) {
        initComponents();
        this.ecoSystem = business;
        this.userProCont = userProcessContainer;
        this.pat = p;
        this.userAcc = account;
        fNameTxt.setText(p.getpFirstName());
        lNameTxt.setText(p.getpLastName());
        addressTxt.setText(p.getpAddress());
        ageTxt.setText(Integer.toString(p.getpAge()));
        genderTxt.setText(p.getpGender());
        insuranceIDTxt.setText(p.getpHealthInsuranceID());
        mobileTxt.setText(p.getpPhoneNo());
        insuranceStatusTxt.setText(p.getpInsuranceStatus());
        populateBillTable();
    }
          private void populateBillTable() {
        DefaultTableModel model = (DefaultTableModel) talbleForBilling.getModel();

        model.setRowCount(0);

        for (PatientBills b : pat.getpBills()) {

            Object[] row = new Object[7];
            row[0] = b.getName();
            row[1] = b.getOrgType();
            row[2] = b.getAmount();
            model.addRow(row);

        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        talbleForBilling = new javax.swing.JTable();
        lblPPhone = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        lblPAddress = new javax.swing.JLabel();
        insuranceIDTxt = new javax.swing.JTextField();
        lblPInsuranceID = new javax.swing.JLabel();
        genderTxt = new javax.swing.JTextField();
        lblPGender = new javax.swing.JLabel();
        mobileTxt = new javax.swing.JTextField();
        fNameTxt = new javax.swing.JTextField();
        lblPFirstName = new javax.swing.JLabel();
        ageTxt = new javax.swing.JTextField();
        lblPAge = new javax.swing.JLabel();
        lNameTxt = new javax.swing.JTextField();
        lblPLastName = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        insuranceStatusTxt = new javax.swing.JTextField();
        lblInsStatus = new javax.swing.JLabel();

        setBackground(new java.awt.Color(153, 153, 0));
        setForeground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Customer Status");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 680, -1));
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 1295, 10));

        talbleForBilling.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        talbleForBilling.setBackground(new java.awt.Color(255, 255, 204));
        talbleForBilling.getTableHeader().setFont(new java.awt.Font("Trebuchet MS", 1, 16));
        talbleForBilling.setFont(new java.awt.Font("Trebuchet MS", 1, 12));
        talbleForBilling.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Item Name", "Organization", "Amount"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(talbleForBilling);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 170, 730, 380));

        lblPPhone.setBackground(new java.awt.Color(255, 255, 255));
        lblPPhone.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPPhone.setForeground(new java.awt.Color(255, 255, 255));
        lblPPhone.setText("Phone Number");
        add(lblPPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 470, -1, -1));

        addressTxt.setEditable(false);
        addressTxt.setBackground(new java.awt.Color(255, 255, 153));
        addressTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressTxtActionPerformed(evt);
            }
        });
        add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 150, 30));

        lblPAddress.setBackground(new java.awt.Color(255, 255, 255));
        lblPAddress.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPAddress.setForeground(new java.awt.Color(255, 255, 255));
        lblPAddress.setText("Address");
        add(lblPAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        insuranceIDTxt.setEditable(false);
        insuranceIDTxt.setBackground(new java.awt.Color(255, 255, 153));
        insuranceIDTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceIDTxtActionPerformed(evt);
            }
        });
        add(insuranceIDTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 150, 30));

        lblPInsuranceID.setBackground(new java.awt.Color(255, 255, 255));
        lblPInsuranceID.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPInsuranceID.setForeground(new java.awt.Color(255, 255, 255));
        lblPInsuranceID.setText("InsuranceID");
        add(lblPInsuranceID, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 106, -1));

        genderTxt.setEditable(false);
        genderTxt.setBackground(new java.awt.Color(255, 255, 153));
        genderTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                genderTxtActionPerformed(evt);
            }
        });
        add(genderTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 420, 150, 30));

        lblPGender.setBackground(new java.awt.Color(255, 255, 255));
        lblPGender.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPGender.setForeground(new java.awt.Color(255, 255, 255));
        lblPGender.setText("Gender");
        add(lblPGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 420, 70, -1));

        mobileTxt.setEditable(false);
        mobileTxt.setBackground(new java.awt.Color(255, 255, 153));
        add(mobileTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 470, 150, 30));

        fNameTxt.setEditable(false);
        fNameTxt.setBackground(new java.awt.Color(255, 255, 153));
        add(fNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 166, 150, 30));

        lblPFirstName.setBackground(new java.awt.Color(255, 255, 255));
        lblPFirstName.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblPFirstName.setText("First Name");
        add(lblPFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, 116, -1));

        ageTxt.setEditable(false);
        ageTxt.setBackground(new java.awt.Color(255, 255, 153));
        ageTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ageTxtActionPerformed(evt);
            }
        });
        add(ageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 370, 150, 30));

        lblPAge.setBackground(new java.awt.Color(255, 255, 255));
        lblPAge.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPAge.setForeground(new java.awt.Color(255, 255, 255));
        lblPAge.setText("Age");
        add(lblPAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 370, 50, -1));

        lNameTxt.setEditable(false);
        lNameTxt.setBackground(new java.awt.Color(255, 255, 153));
        lNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lNameTxtActionPerformed(evt);
            }
        });
        add(lNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 150, 30));

        lblPLastName.setBackground(new java.awt.Color(255, 255, 255));
        lblPLastName.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblPLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblPLastName.setText("Last Name");
        add(lblPLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 116, -1));

        backBtn.setBackground(new java.awt.Color(0, 153, 204));
        backBtn.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 14)); // NOI18N
        backBtn.setForeground(new java.awt.Color(255, 255, 255));
        backBtn.setText("Back");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        add(backBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 80, 30));

        insuranceStatusTxt.setEditable(false);
        insuranceStatusTxt.setBackground(new java.awt.Color(255, 255, 153));
        add(insuranceStatusTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 520, 150, 30));

        lblInsStatus.setBackground(new java.awt.Color(255, 255, 255));
        lblInsStatus.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 18)); // NOI18N
        lblInsStatus.setForeground(new java.awt.Color(255, 255, 255));
        lblInsStatus.setText("Insurance Status");
        add(lblInsStatus, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void addressTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressTxtActionPerformed

    private void insuranceIDTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceIDTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceIDTxtActionPerformed

    private void ageTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ageTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ageTxtActionPerformed

    private void lNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lNameTxtActionPerformed

    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
        // TODO add your handling code here:
        //patient.setInsuranceStatus("Approved");
        InsuranceWorkAreaJPanel bill = new InsuranceWorkAreaJPanel(userProCont, userAcc, ecoSystem);
        userProCont.add("Insurance main", bill);
        CardLayout layout = (CardLayout) userProCont.getLayout();
        layout.next(userProCont);
    }//GEN-LAST:event_backBtnActionPerformed

    private void genderTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_genderTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_genderTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField ageTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.JTextField fNameTxt;
    private javax.swing.JTextField genderTxt;
    private javax.swing.JTextField insuranceIDTxt;
    private javax.swing.JTextField insuranceStatusTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lNameTxt;
    private javax.swing.JLabel lblInsStatus;
    private javax.swing.JLabel lblPAddress;
    private javax.swing.JLabel lblPAge;
    private javax.swing.JLabel lblPFirstName;
    private javax.swing.JLabel lblPGender;
    private javax.swing.JLabel lblPInsuranceID;
    private javax.swing.JLabel lblPLastName;
    private javax.swing.JLabel lblPPhone;
    private javax.swing.JTextField mobileTxt;
    private javax.swing.JTable talbleForBilling;
    // End of variables declaration//GEN-END:variables
}
